### ISSUE TITLE
GSoC 2019 - Add a template for all blogs

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#1]
This task is to add an initial template for displaying all blogs on the platform, the layout should fit with the mainpage [http://python-gsoc.org/](http://python-gsoc.org/)

**Comment by sounak98** [comment]
@botanicvelious I would like to take this issue up, can you assign it to me?

**Comment by botanicvelious** [comment]
Sure, you can see a page with all posts at http://127.0.0.1:8000/en/student-blogs/gsoc-2019/

The theme should match http://python-gsoc.org/

**Comment by botanicvelious** [comment]
I just realised the student-blogs/gsoc-2019/ url was something i was testing and didnt work properly. You would have to use http://127.0.0.1:8000/en/blog/

**Comment by sounak98** [comment]
@botanicvelious can you review the changes?
And also, do we want any template styling for the blogs? Or any footer?

**Comment by botanicvelious** [comment]
the style should match [http://python-gsoc.org/](http://python-gsoc.org/) exactly, its getting there but it needs more work.
