### ISSUE TITLE
GSoC 2019 - Use pure.css as much as possible

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#102]
There is a good deal of css that is not diretly using pure.css, this will take modifying templates etc to be able to use pure.css for all of it and make it work.

**Comment by Mihir-Karbelkar** [comment]
I would like to work on this as my first issue. Any head start?

**Comment by botanicvelious** [comment]
not sure what you mean by a head start but go for it! 👍

**Comment by Mihir-Karbelkar** [comment]
By head start I meant how should I go about doing this... Usually whenever I work on any new open source project I ask this but then I realised it is css. Thanks :)

**Comment by sharmaadityaHQ** [comment]
Sir @botanicvelious can i take this up if @Mihir-Karbelkar is not working on this?

**Comment by botanicvelious** [comment]
go for it

**Comment by Mihir-Karbelkar** [comment]
Yes please, I am little stuck in exams🙂

**Comment by sharmaadityaHQ** [comment]
if @sounak98 you can take this up. I am busy with a exam and will get back to other issues soon.

**Comment by Mihir-Karbelkar** [comment]
Well I have submitted a pr for this ( if anyone wants to know if this issue is open).

**Comment by botanicvelious** [comment]
https://python-gsoc.org/deadlines.html 

mobile issues:

Text too small to read 
Clickable elements too close together 
Content wider than screen

**Comment by botanicvelious** [comment]
If I was to guess its the calendar looks like we gotta do agenda mode on mobile

https://answers.squarespace.com/questions/54774/how-to-embed-a-google-calendar-in-a-responsive-way.html

**Comment by sounak98** [comment]
> https://python-gsoc.org/deadlines.html
> 
> mobile issues:
> 
> Text too small to read
> Clickable elements too close together\

Is it for the cms specific elements?

> Content wider than screen\

afiak this only happens when you click on the menu

**Comment by botanicvelious** [comment]
Also need to cleanup css colors etc on blog pages, maby alternate colors etc?

**Comment by botanicvelious** [comment]
www and blogs sidebar and fonts also dont match. 

There is also dead click space on the blog cards

https://blogs.python-gsoc.org/en/ should be alphabetical for the blog cards

for ckeditor prolly good to limit font sizes etc for a more consistent look also
