### ISSUE TITLE
GSoC 2019- Operational error on clicking My Profile in sidebar on admin page

### ISSUE THREAD

**Issue by sharmaadityaHQ** [python-gsoc/python-blogs#108]
This bug is encountered on clicking My Profile in sidebar on Admin page.

Request URL: | http://127.0.0.1:8000/en/myprofile/

1. Go to http://127.0.0.1:8000/en/. Login to admin page.
2. Click on My Profile in sidebar.
3. See error

**Expected behavior**
My Profile option on admin page should provide details of the admin.

**Desktop :**
 - OS: Ubuntu 18.04
 - Browser: Firefox

**Comment by sounak98** [comment]
@botanicvelious this is because the db hasn't been migrated with the latest migration.
