### ISSUE TITLE
Move settings to separate config

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#119]
We need to load a settings file from settings.py for stuff like the key etc.

**Comment by sharmaadityaHQ** [comment]
I would like to take this up.Could  you @botanicvelious pls guide me what exactly is to be done.

**Comment by botanicvelious** [comment]
http://fearofcode.github.io/blog/2013/01/15/how-to-scrub-sensitive-information-from-django-settings-dot-py-files/ is an example of how to do it

Need to remove the settings from settings.py and move it to like a example_settings_secret.py then load from settings_secret.py

**Comment by sounak98** [comment]
@sharmaaditya570191 still working on this?

**Comment by sharmaadityaHQ** [comment]
@sounak98 I will submit a PR soon.

**Comment by sharmaadityaHQ** [comment]
Sir @botanicvelious I have submitted a PR. Please review it.
