### ISSUE TITLE
redirect to proper url

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#127]
When you register via a link such as https://blogs.python-gsoc.org/accounts/register?reglink_id=b7b47def-42b8-442e-b422

If you input a already used username then it redirects you to https://blogs.python-gsoc.org/accounts/register not https://blogs.python-gsoc.org/accounts/register?reglink_id=b7b47def-42b8-442e-b422

**Comment by sharmaadityaHQ** [comment]
I would like to take this up @botanicvelious.

**Comment by botanicvelious** [comment]
Also, it should fill in the email as it does normally, on a submit error it clears the email field.

**Comment by ghost** [comment]
I'll take this up since no update from @sharmaaditya570191
