### ISSUE TITLE
Shows blank page when there are no blogs

### ISSUE THREAD

**Issue by sounak98** [python-gsoc/python-blogs#133]
When there are no blogs, the blogs page shows a blank page instead of some message. Minor issue though, because this situation will never arise after the first GSoC conducted on this platform.

![Screenshot 2019-04-24 at 4 52 56 PM](https://user-images.githubusercontent.com/22390515/56656008-fc523000-66b1-11e9-9bcf-36baa3f3d69b.png)

**Comment by ghost** [comment]
@sounak98 I remember fixed this the other day. Can you pull upstream repo and see if it still occurs? :)

**Comment by sounak98** [comment]
I just checked the version on the server which is behind the current master I'm pretty sure. So it might be actually implemented already.

Edit: @ntkomata I checked it out, there's no error message or something. Nevermind, I'll fix this, just a few lines of code. 😄
