### ISSUE TITLE
Will a user have more than 1 student profile?

### ISSUE THREAD

**Issue by ghost** [python-gsoc/python-blogs#142]
The current code can't handle multiple student profiles in one user which is easy to fix. but I'm wondering if a user should have more than 1 student profile? like if the student is participating in more than 1 suborg? or the student will have multiple user accounts? This has something to do with the proposal upload and other things @botanicvelious

**Comment by sounak98** [comment]
One user can have two profiles (even student profiles). Think of the scenario where one student gets selected twice for GSoC.

Check this out https://github.com/python-gsoc/python-blogs/blob/master/gsoc/models.py#L100

**Comment by ghost** [comment]
I guess I'll create a proposal upload section for each student profile
