### ISSUE TITLE
Create new blog tab moves out of window

### ISSUE THREAD

**Issue by kaybhutani** [python-gsoc/python-blogs#180]
**Describe the bug**
The create new blog tab moves out of window once you drag it and there is no way to bring it back. If you are using interact.js, I suggest to have max x and y axis deviation limit.

![Screenshot from 2019-05-28 23-42-16](https://user-images.githubusercontent.com/32310179/58502326-eef1ff00-81a3-11e9-9093-4fe233761989.png)

**Comment by botanicvelious** [comment]
issue is in django cms, also very hard to do as the mouse pointer gets limited to the window. not much of a way to fix it on our side easly.
