### ISSUE TITLE
Cannot edit own blog post

### ISSUE THREAD

**Issue by sappelhoff** [python-gsoc/python-blogs#182]
**Describe the bug**
Trying to edit my **own** blog post by "double clicking" on the post will return a "permission not granted" message.

**To Reproduce**
1. Write a blog post
2. Look at the post
3. Hover over the text to see "Double-click to edit text"

**Expected behavior**
I should be able to double click, edit the text, and then save ... given that it's my own blog post.

**Screenshots**
![image](https://user-images.githubusercontent.com/9084751/58508483-6b7ce180-8194-11e9-9799-a55b33ef5b1b.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Firefox
 - Version: 67

**Comment by sounak98** [comment]
@sappelhoff hope you can edit your blogs now. Cheers!

**Comment by sappelhoff** [comment]
It works, thanks @sounak98 :)
