### ISSUE TITLE
Error while submitting blog posts

### ISSUE THREAD

**Issue by vipulgupta2048** [python-gsoc/python-blogs#187]
**Describe the bug**

Tried submitting a post, got an error and the content was lost. Error is as follows

![Screenshot_2019-05-29_15-26-42](https://user-images.githubusercontent.com/22801822/58548394-db3bac80-8226-11e9-804b-f64d70d5e1a6.png)

I am sure this is not the error what I saw, I am thinking something is characters being used is causing an issue. This could be a false alarm as well, I might have added something that shouldn't be there. 

**To Reproduce**
1. Went to my blogs url - https://blogs.python-gsoc.org/en/blogs/vipulgupta2048s-blog/
2. Click on `Create`
3. Filled the fields with content regarding my post
4. Clicked `Create` to submit the post and the error. 

**Expected behavior**
The post should have been submitted with the content present as formatted.

**Desktop (please complete the following information):**
 - Xubuntu 18.04
 - Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Additional context**
If you see, https://blogs.python-gsoc.org/en/blogs/vipulgupta2048s-blog/ you can see the heading of the blog post, but no content. I will try to recreate my original steps to get the same error I was getting last time. I am happy to help in any way I can.

**Comment by sounak98** [comment]
@vipulgupta2048 what was the text that you were trying to put as content?

**Comment by vipulgupta2048** [comment]
Well, I tried recreating the last post's content which was the one that failed hence copied all the content from [here](https://blogs.python-gsoc.org/en/blogs/vipulgupta2048s-blog/1-the-week-that-has-been-2048/) and pasted it as a new post.

**Comment by botanicvelious** [comment]
should be fixed now, was a mysql utf8 issue

**Comment by botanicvelious** [comment]
should be fixed now, was a mysql utf8 issue

**Comment by vipulgupta2048** [comment]
Thanks @botanicvelious !
