### ISSUE TITLE
Not able to delete blog

### ISSUE THREAD

**Issue by vipulgupta2048** [python-gsoc/python-blogs#199]
**Describe the bug**
I am not sure why these exceptions have with me :laughing: but now I am not able to delete a blog I wrote. Here's the blog, I accidentally created and is not being deleted - https://blogs.python-gsoc.org/en/blogs/vipulgupta2048s-blog/some-bits-about-my-community-alias/

![Screenshot_2019-06-01_22-52-56](https://user-images.githubusercontent.com/22801822/58751724-11e02400-84c0-11e9-95c5-b75ed574fbb4.png)

**To Reproduce**
1. Was working with source code mode for writing and editing the blog.
2. Accidentally clicked `Create` to create the post. 
3. Get this error, as shown above when deleting

**Expected behavior**
The selected post should be deleted.

*Desktop (please complete the following information):*

- Xubuntu 18.04
- Chrome
- Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by vipulgupta2048** [comment]
Let me know if I can help you folks in any way to solve this

**Comment by sounak98** [comment]
@vipulgupta2048 students don't have permissions to delete blogs. So if you need a blog deleted, you will need to contact the admin.

**Comment by vipulgupta2048** [comment]
Hi @sounak98 but, 
1. I have deleted my own blogs before, only now I have seen this happening.
2. My Org Admin, you mean?

**Comment by sounak98** [comment]
Yeah, changed the permissions now. And no I mean gsoc-admins@python.org.

**Comment by vipulgupta2048** [comment]
Right, thanks!
Closing this issue.

**Comment by sounak98** [comment]
@vipulgupta2048 after #207 gets merged, you will be able to unpublish a blog if you want to keep it away from the whole world and publish it back later. And also now editing a blog works!

**Comment by vipulgupta2048** [comment]
That works @sounak98 Thanks for solving that!! 
This would help the writers a lot, maybe announce it on the mailing list as well.
