### ISSUE TITLE
GSoC 2019 - Add sitewide RSS feed

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#2]
This task is to create a page that will return an RSS feed of all blog posts.

For information on what an RSS feed looks like you can reference [https://www.w3schools.com/xml/xml_rss.asp](https://www.w3schools.com/xml/xml_rss.asp)

**Comment by shashank-sharma** [comment]
@botanicvelious Just wanted to clarify, how is it different from what we have already at link: http://127.0.0.1:8000/en/blog/feed/

![screenshot from 2019-02-13 20-05-27](https://user-images.githubusercontent.com/9320644/52719046-cebe7b80-2fca-11e9-8f34-cd528d986e42.png)

**Comment by botanicvelious** [comment]
my bad i forgot i had added it
