### ISSUE TITLE
Adding user throws error

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#21]
if you add a user you get the error

no such table: cms_pageuser

Request Method: | POST
-- | --
http://127.0.0.1:8000/en/admin/auth/user/add/
1.11.20
OperationalError
no such table: cms_pageuser
C:\Python36\lib\site-packages\django\db\backends\sqlite3\base.py in execute, line 328
C:\Python36\python.exe
3.6.8
['D:\\development\\python-blog\\python-blogs',  'C:\\Python36\\python36.zip',  'C:\\Python36\\DLLs',  'C:\\Python36\\lib',  'C:\\Python36',  'C:\\Python36\\lib\\site-packages']
Wed, 13 Feb 2019 14:29:14 -0800

**Comment by shashank-sharma** [comment]
I remember seeing this error and I was planning to push in next code. I'll take this issue. I guess it takes 1 line of code

**Comment by botanicvelious** [comment]
I would imagine it is related to the dual database setup.
