### ISSUE TITLE
Upgrade to Django CMS 3.7 & Django 2.2

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#27]
This is for tracking the upgrade to the django lts and django cms lts release that will be out just before GSoC starts.

Nothing to do on this just yet... but we should try and keep it in mind and get as close as possible to avoid major work at that point. Pretty important to be on the lts release's so that maintenance is easier.

**Comment by sounak98** [comment]
@botanicvelious django CMS can be upgraded to 3.7.0rc1 but upgrading to Django 2.2.x throws an error on running any django management commands.

For more info: https://github.com/divio/django-cms/issues/6717
