### ISSUE TITLE
auto add mentors in google

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#287]
auto connect to google gsoc and invite a mentor when they make an account

**Comment by botanicvelious** [comment]
Get org ID

https://summerofcode.withgoogle.com/api/om/program/current/membership/
```
{
  "results": [
    {
      "organization_id": 6017901476184064
    }
  ]
}
```

POST request

```
https://summerofcode.withgoogle.com/api/om/program/2019/organization/6017901476184064/invite/
post
Host: summerofcode.withgoogle.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:68.0) Gecko/20100101 Firefox/68.0
Accept: application/json, text/plain, */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://summerofcode.withgoogle.com/dashboard/org-admin/members/invite/
X-CSRFToken: ...
Content-Type: application/json;charset=utf-8
X-Content-Type-Options: nosniff
Content-Length: 46
Connection: keep-alive
Cookie: page-size=100; ...
TE: Trailers
with a request body of {"email":"email@gmail.com","role":"2"}
```

**Comment by ghost** [comment]
Is this implemented?

**Comment by botanicvelious** [comment]
Not as of yet, we started on it but ran out of time, as google login process is wonky

**Comment by Amanhacker** [comment]
Hello, I am new contributing to Python and Machine Learning and I am really interested in solving this issue.
If this issue is still open can I work on this, and can you help me with how I can have a start.

**Comment by safwan20** [comment]
hello !! I want to work on this issue

**Comment by botanicvelious** [comment]
this is not something that can be done at this point as it requires access to a google system that only exists during gsoc coding
