### ISSUE TITLE
GSoC 2019 - Create form for suborg submissions

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#3]
This task is to create a form that when submitted will enter the input data into the database.

The form fields are as follows:

>Your details:
>
>Why does your org want to participate in Google Summer of Code?
>
>How many potential mentors have agreed to mentor this year?
>
>Suborg Admin Email
>
>Mentors Emails
>
>How will you keep mentors engaged with their students?
>
>How will you help your students stay on schedule to complete their projects?
>
>How will you get your students involved in your community during GSoC?
>
>How will you keep students involved with your community after GSoC?
>
>Has your org been accepted as a mentor org in Google Summer of Code before?
>
>Which years did your org participate in GSoC?
>
>Was this as a Suborg?
>
>For each year your organization has participated, provide the counts of successful and total students. (e.g. 2016: 3/4)
>
>If your org has applied for GSoC before but not been accepted, select the years:
>
>What year was your project started?
>
>Where does your source code live?
>
>Please provide URLs that point to repositories, GitHub organizations, or a web page that describes how to get your source code.
>
>Anything else we should know (optional)?
>
>
>
>Public Profile
>
>Name
>
>Website URL
>
>A very short description of your organization.
>
>Your organization logo. Must be a 24-bit PNG, minimum height 256 pixels.
>
>Primary Open Source License
>
>Ideas List
>
>You must complete at least one of the following three contact options:
>
>Chat
>Link to a web page that describes how to get on your IRC channel or other realtime communication system.
>
>Mailing List
>Link to a page describing how to join your organization's mailing list.
>
>Links
>
>Twitter URL (optional)
>
>Blog URL (optional)

**Comment by nightwarriorftw** [comment]
@botanicvelious I would love to work on this issue. Can I ?

**Comment by botanicvelious** [comment]
go for it, do you have any questions on what needs to be done?

**Comment by botanicvelious** [comment]
Please keep in mind this would likely best be done via a Page Application, ie an apphook

[docs.django-cms.org/en/release-3.5.x/how_to/apphooks.html](http://docs.django-cms.org/en/release-3.5.x/how_to/apphooks.html) 
[docs.django-cms.org/en/release-3.5.x/introduction/apphooks.html](http://docs.django-cms.org/en/release-3.5.x/introduction/apphooks.html)

This would mean to use the form you would 

> Create the new page.
> In its Advanced settings, choose "Suborg Form" in the Application field.

**Comment by nightwarriorftw** [comment]
Sure I will try my best and will work on different branch for this.

**Comment by nightwarriorftw** [comment]
@botanicvelious Can I use animations too ? Because it gives a great effect. Moreover please respond on IRC whenever you are free .
Thanks

**Comment by botanicvelious** [comment]
go for it! make it look pretty!

**Comment by ujjwalll** [comment]
Can I work on this issue as well?

**Comment by botanicvelious** [comment]
@ujjwalll it looks like @nightwarrior-xxx is working on this one already, as such I added a similar issue #33 that you can take if you would like, just post in the issue that you will be working on it.

**Comment by MastersAbh** [comment]
Hey @botanicvelious , Nothing's been heard on this issue. Can I take this one after I'm done with my last PR ?

**Comment by nightwarriorftw** [comment]
@MastersAbh I am working on this  :D
I have made the modals you can help with left out things 
[Its here](https://github.com/nightwarrior-xxx/python-blogs/commit/7a5079e2e2045a3f9df0ab1ac49f37a9e7a2d526)

**Comment by Karna98** [comment]
I'm working on this Issue.
