### ISSUE TITLE
Extend runcron management command

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#31]
This task is to extend the runcron command so that it reads from a "scheduler" model and does the tasks as specified when manage.py runcron process_items is called. 

The schdeuler model would have 3 fields, one field would be the "command" to run, the other would be the "data", the last would be a "success" field. Storing the items in the data field in the model in json would probably be easiest. 

For example, the model would include things such as "send_email" which would take the "data" field and call the sendemail function. 

You will also need to add arguments to runcron for "build_items" and "process_items" as well as when ran without arguments it would run build_items then process_items in order.

**Comment by sounak98** [comment]
We can use the `runcron` command to send the IRC messages also right?

**Comment by botanicvelious** [comment]
Thats the plan! Send_email is just one example, this scheduler would also be used for the irc messages etc as needed.

**Comment by sounak98** [comment]
The functions I wrote for sending a message to IRC doesn't run when called inside a controller because the event cycle runs in a different thread than the one that handles the server. So this will be a viable solution.

I will start working on the scheduler and then integrate the `send_irc_message` function with it.

**Comment by botanicvelious** [comment]
great! hit me up on irc if you have any questions about the design etc.

**Comment by botanicvelious** [comment]
After thinking about it I think a multiprocessing Pool would probably be the best way to implement this for the process_items part. 

another table with process_items_settings would be good, that way we could put in settings like "timeout" and "num_workers" that would be used when there is no specific settings set in the command.

Additionally then for testing, we can do something like ''manage.py runcron process_items --timeout=10 --num_workers=5

**Comment by sounak98** [comment]
We can use `settings.py` for the default fallback options, right? Why is there a need of making a separate table for it?

**Comment by botanicvelious** [comment]
Could use settings.py I suppose for the defaults, however, a database table would allow it to be changed easier in the admin web interface. Could always change it to use a table later if there is ever a need, so if settings.py is easier for now just go with that.
