### ISSUE TITLE
Show blog post previews instead of expanding whole blog post in the Overview page

### ISSUE THREAD

**Issue by jaladh-singhal** [python-gsoc/python-blogs#322]
Hello team,
First of all I want to thank you for developing such a great blogging platform for PSF GSoC students. I've blogging there each week but as the no. of blogs increased, I (or anyone who visits my blog) face problem in navigating all of my blog posts at once. 

The overview page (main landing page of any [user's blog](https://blogs.python-gsoc.org/en/jaladh-singhals-blog/)) shows all blog posts in expanded form. This makes only 5-6 blog post appear on a page. And anyone who might not be interested to read, say Week-8 to 6 posts, then he has to scroll the entire page down to reach Week-5 post. This is really frustrating for reader - he should just get a glimpse of each blog post before he actually decides to open & read the entire post!

I suggest to make Overview page show only a glimpse of each blog post with a "read more...", instead of expanding it fully therein. For example you can check overview page of [Sunpy's blog](https://sunpy.org/blog/category/gsoc). I believe this way PSF blog will actually comply with the meaning of Overview i.e. to show only a preview of all available posts instead of their expanded views.
   
Additionally you could also consider to show a TOC sidebar in a user's blog, listing titles of all blog posts by the user. Though I would prefer the former suggestion which will also show a preview of post besides only the title.

Thanks again for the great work & constant improvements you've did, I believe you'll also incorporate this feature to make PSF blog more user friendly!

Regards,
Jaladh Singhal,
GSoC'19 student at StarKit (PSF's suborg)

**Comment by ayushiitr2901** [comment]
Hi, I am new contributing to Python and I am really interested in solving this issue.
If this issue is still open can I work on this, and can you help me with how I can have a start.

**Comment by sounak98** [comment]
Hey @ayushiitr2901 the blogs list was intentionally kept this way. Although you could probably try to implement the TOC to be displayed above the blog post in the blog post view (not the blogs list view), that would be a good idea.

If you are facing any problems do drop a comment or a WIP pull, I will try to help you out.

**Comment by ayushiitr2901** [comment]
I think the idea is to display a 'Table of Contents' that links to the different sections of a blog post within the page in the blog post view like (https://blogs.python-gsoc.org/en/jaladh-singhals-blog/week-11-from-interactive-notebooks-to-web-apps/).
Please approve if I am right, and I will start working on it.
Thank you for helping!

**Comment by botanicvelious** [comment]
What would be good is maby a floating sidebar on the right with all the blogs.

Something like on 

https://www.law.cornell.edu/uscode/text/5/504

where on the right it has a box with "U.S. Code Toolbox"

not the same as what is there but same concept

you can find me on irc @freenode in the #python-gsoc channel, just say botanic and i should see the message

**Comment by sounak98** [comment]
@ayushiitr2901 keeping in mind the responsiveness of the page, you can make it go to the top when the browser width is smaller or even hide it for that matter.

**Comment by ayushiitr2901** [comment]
Dear, developers I have made a pull request regarding the same, Please review it and I apologize for the delay, I was busy with some urgent campus project.

**Comment by jaladh-singhal** [comment]
@botanicvelious @sounak98 Thank you for considering this. But as per this discussion, I think you're deviating from the actual feature request. 

I am requesting a blog previews (blogs list on overview page showing glimpse of each blog post's content) like [here](https://sunpy.org/blog/category/gsoc). 

Please let me know if I can help further in making this issue more clear.

**Comment by botanicvelious** [comment]
i understand however the other admins decided they wanted it done this way, thats why i was looking at ideas that would give a better user experience and at least help with the issue you were having

**Comment by priyanshu-panwar** [comment]
@jaladh-singhal I got it how you want to have them displayed. You want only the first few lines to be displayed followed by "Read More".
I ll try fixing it now.
