### ISSUE TITLE
GSoC 2019 - Add Student Menu Form

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#33]
issue #37 is related

We need to have an admin menu item for adding students to the platform. 

The admin toolbar item would need to have the following

1) Form for adding students with the following fields, email, name, project, suborg, year and all fields required to be filled in
2) A "+" for adding more than one student at a time in a form list.
3) The suborg and year would be selectable from the current model as a dropdown
4) After submitting the form it would add a user with those settings for each item in the form list

**Comment by ujjwalll** [comment]
I would like to work on this task, I am supposed to create a page through which admin can add students to the database?

**Comment by botanicvelious** [comment]
correct, however, the fields for the creation of the user would have the fields above as well as allow for adding multiple at the same time so something similer to [http://outbottle.com/wp-content/uploads/2012/08/add_remove_from_dynamic_list.png](http://outbottle.com/wp-content/uploads/2012/08/add_remove_from_dynamic_list.png) just with the correct fields and items etc

Also I added some test data for the gsoc model to the repo database so you will want to pull that. The gsoc year should be a dropdown selection with the most current year preselected, the gsoc suborg would be an alphabetical dropdown selection with no preselected item.

If you have any questions I am on irc and will be online for at least another hour.
