### ISSUE TITLE
[BUG] Builtin RSS feed strips posts

### ISSUE THREAD

**Issue by sappelhoff** [python-gsoc/python-blogs#336]
I wrote a blog during the GSoC 2019: https://blogs.python-gsoc.org/en/sappelhoffs-blog/

... and I would like to download all my posts.

Is there a convenient way to do this? I think it would be a nice feature if there were a "download my data" button, that grabs all raw blog content and downloads it as a zip file.

As far as I see it currently, I would have to go through each post and manually download by either using copy/paste, or my browser options.

**Comment by botanicvelious** [comment]
you can get the text of your blog from your personal rss feed at
https://blogs.python-gsoc.org/en/sappelhoffs-blog/feed

**Comment by sappelhoff** [comment]
That sounds great, thanks! ... interestingly the rss feed does not provide me with the three earliest blog posts. Any idea, why?

**Comment by botanicvelious** [comment]
looks like the built in feed strips posts, will be fixed soon!

**Comment by botanicvelious** [comment]
you can now get all blogs from https://blogs.python-gsoc.org/en/feed/sappelhoffs-blog/

**Comment by sappelhoff** [comment]
Thanks @botanicvelious  :+1:
