### ISSUE TITLE
GSoC 2019 - Create Page For All Blogs

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#34]
For this issue, you will need to add a few blogs to the system. There is an example "Student Blogs" page already. you can add more by following [https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html](https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html).

Additionally you will need to add some users that are assigned to the "students" group and have a suborg and year set on them.

This task is to make a single page that displays all blogs on the system together by year. An example would be something like [https://blogs.python-gsoc.org/](https://blogs.python-gsoc.org/) for each year, newest to oldest

**Comment by sounak98** [comment]
@botanicvelious so the different students will have separate blogs for them?

**Comment by botanicvelious** [comment]
yes, each student has there own blog however this is a page to combine all of those separate blogs into a single page. something along the lines of "select pages where app = blog"

**Comment by MastersAbh** [comment]
@botanicvelious , I made two separate blogs, which contain articles by different users. So, on the common page, how exactly should it be displayed? 

Is it like this:

Blogs of all the users with same suborg and year be displayed together
and
The blogs would contain all the articles made by that particular user.

**Comment by MastersAbh** [comment]
@botanicvelious  you there? I am unable to contact you.

**Comment by botanicvelious** [comment]
It would be a page like https://blogs.python-gsoc.org/ one block for each year.

**Comment by MastersAbh** [comment]
One block for each year ??
So, suppose we go inside 2016 blog(say, test1). So, on entering that block, all the articles belonging to test1 should be displayed?

**Comment by botanicvelious** [comment]
Somethin like https://i.imgur.com/P93xsp4.png

**Comment by ghost** [comment]
@MastersAbh  still working on this??

**Comment by MastersAbh** [comment]
Yes, I am still on it

**Comment by ghost** [comment]
good

**Comment by sounak98** [comment]
There has been no update for a long time @MastersAbh, should I take this up?

**Comment by gideononyewuenyi** [comment]
i will be working on this

**Comment by sounak98** [comment]
@codewithgideon this has been fixed by #140
