### ISSUE TITLE
HTML/CSS of blog post not getting rendered for first few minutes

### ISSUE THREAD

**Issue by jaladh-singhal** [python-gsoc/python-blogs#344]
Hello team, 
Since last two weeks, I'm observing that as soon as I create a blog post, it doesn't get rendered but shows HTML/CSS for it. This behavior is same even when I edit the blog post.

As soon as I create/edit blog post: 
![blogunpub](https://user-images.githubusercontent.com/36361463/63530299-cfa90a80-c523-11e9-879b-cd81cd52dcf9.png)

After about 15-20 minutes (I've checked this time gap):
![blogpub](https://user-images.githubusercontent.com/36361463/63530311-d59eeb80-c523-11e9-945c-61564ffafe79.png)

It's strange that it was not the case 2 weeks ago. I was able to see the changes (or a new post) I made, in rendered form as soon as I save it. But it doesn't happen any longer. Also I'm not sure if it is the case only with me or with other students as well.

Please let me know if I can help you further, anyhow. And thanks for creating & maintaing such a great blogging platform.

**Comment by sounak98** [comment]
@jaladh-singhal thanks for posting this bug. We will work on this and fix it ASAP!
