### ISSUE TITLE
GSoC 2019 - Create permissions setup for student.

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#35]
>For this issue, you will need to add a few blogs to the system. There is an example "Student Blogs" page already. you can add more by following [https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html](https://aldryn-newsblog.readthedocs.io/en/latest/how-to/apphook_configurations.html).

This issue is to create the setup for a student user. This user would have to have permissions to edit and post to one blog but no other pages etc.

**Comment by botanicvelious** [comment]
This may require some lower level changes see [#368](https://github.com/divio/aldryn-newsblog/issues/368)

**Comment by sounak98** [comment]
Will look into this
