### ISSUE TITLE
when editing timeline dates update builders

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#356]
Builders dont change there dates when a timeline object has its date changed

**Comment by kunakl07** [comment]
Hi, I would like to work on this project. Could you please help me with where to start so that I would start working on it.

**Comment by botanicvelious** [comment]
if you goto en/admin/gsoc/timeline/ and select a timeline, then add and change the date on an item from it that is of the blog post type,  you will see in en/admin/gsoc/builder/ that the builders that were created are still there with the old date

**Comment by kunakl07** [comment]
I am sorry as  I am not able to find the location that you've given(I am neither able to find it in python-blogs nor in starkit). I would be grateful if you could share the link.

**Comment by botanicvelious** [comment]
That is the web url, you will need to run the blog code then goto that url, for example http://localhost/en/admin/gsoc/timeline/

**Comment by kunakl07** [comment]
Oh got it, I am sorry for asking such a lame question.

**Comment by botanicvelious** [comment]
not a problem, the only truly lame questions are those that you dont ask or have asked before 👍
