### ISSUE TITLE
auto add names for timelines based on checkin or blog post

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#358]
the timeline descriptions should be auto created based on if the timeline type is a blog or a weekly check in rather then manual typed in

**Comment by priyanshu-panwar** [comment]
Hello Sir @botanicvelious I want to contribute here. I have a good hand in Python Django Freelance. Can you please tell me from where to start in this issue.

**Comment by botanicvelious** [comment]
When you run the site if you goto admin/gsoc/timeline and create a timeline you will see that there is a field for the title that auto fills in "Weekly Check-in Due" however it would be best if that field was not a box to fill in but that the title was created via the other field to the right "category" and made the title based on the count, for example

May 18, 2020 - 1st Weekly Check-in Due
May 25, 2020 - 1st Weekly Blog Post Due
June 1, 2020 - 2nd Weekly Check-in Due
June 8, 2020 - 2nd Weekly Blog Post Due

etc
