### ISSUE TITLE
GSoC 2019 - Create login page

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#36]
This task is to create a login/logout menu item, and a login page with password reset emails.

**Comment by nightwarriorftw** [comment]
@botanicvelious If you don't mind I would like to pick it up after finishing my current issue .

**Comment by botanicvelious** [comment]
Once you have the other pr in go for it so long as no-one gets to this issue first!

**Comment by Abhishekism9450** [comment]
@botanicvelious Can I work on this issue, if its still open ?

**Comment by botanicvelious** [comment]
go for it!

**Comment by SupreethBaliga** [comment]
Hi. I am new to open source contribution. I am interested in working on this. I am done with the login page layout. But not understanding how to work on the password reset button. Can you please provide some resources on this which I can go through and continue my work on this issue? Thanks.

**Comment by botanicvelious** [comment]
Take a look at https://wsvincent.com/django-user-authentication-tutorial-password-reset/

**Comment by SupreethBaliga** [comment]
Thanks! That will help a lot!

**Comment by jeffysam6** [comment]
can i work on this issue?

**Comment by botanicvelious** [comment]
i think @SupreethBaliga is already working on it, there are some other issues open however.

**Comment by SupreethBaliga** [comment]
No its alright @botanicvelious . I would probably take up a lot more time to learn it. @jeffysam6 can work on it.

**Comment by jeffysam6** [comment]
thank you @SupreethBaliga :)

**Comment by jeffysam6** [comment]
Hello @botanicvelious,
I'm done with creating login/logout menu item  which will redirect to login page and the user can logout.
And i followed the instructions from "https://wsvincent.com/django-user-authentication-tutorial-password-reset/"  but it is not sending a mail to that email address i enter

Should i shoot a PR till what i've done?

**Comment by botanicvelious** [comment]
That is fine, it is possible that your isp blocks email outbound, do you get a connection timeout when you try and send the email?

**Comment by botanicvelious** [comment]
Just make the pr and we can work on it from there

**Comment by jeffysam6** [comment]
#60  done @botanicvelious  :)
