### ISSUE TITLE
creating a suborg application doesnt auto add suborg admin user profile

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#363]
Seems to not add anything?

**Comment by arcriley** [comment]
Suborg admin isn't being assigned but the other mentors are?

**Comment by botanicvelious** [comment]
its when you submit a suborg application form and then accept the suborg as an admin, it doesnt seem to add the profile for the suborg admin

**Comment by terriko** [comment]
Reproducing instructions: create new user (Alice), make sub org admin application (Banana), approve.  When it's approved, we can see that the user Alice isn't a member of the Banana sub-org.

Current problem: can't follow the logic of the creation of the sub org. 

Alternate solution: find a way to assign the user to a sub-org after creation/approval?
