### ISSUE TITLE
GSoC 2019 - Add menu item for adding mentors

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#37]
issue #33 is related

We need to have an admin menu item for adding mentors to the platform.

The admin toolbar item would need to have the following

    1. Form for adding mentors with the following fields, email, name and all fields required to be filled in
    2. A "+" for adding more than one mentor at a time in a form list.
    3. After submitting the form it would add a user with those settings for each item in the form list

**Comment by ashryaagr** [comment]
@botanicvelious I would like to work on this issue . Can I ?

**Comment by botanicvelious** [comment]
go for it!

**Comment by veer11997** [comment]
i want to contribute on it for python gsoc -2019

**Comment by botanicvelious** [comment]
@veer11997 I think @ashryaagr is already working on this issue.

**Comment by veer11997** [comment]
but @ashryaagr  has not contributed yet .so still he is trying or not we  dont know .if he is not working then 
i want to work on it.as your wish....

**Comment by botanicvelious** [comment]
You are welcome to work on it, I just wanted to make sure you were aware @veer11997
