### ISSUE TITLE
more better english

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#379]
student invite email needs work, also update the website so its more clear.

You should be comfortable communicating your ideas to others in public. Most projects have public mailing lists and would prefer if you use them, and Python students are also required to blog about their work over the summer. You can use a pseudonym (nickname) if that works best for you. Google will need to know who you are to pay you, but we just need something to call you.

All students are required to post weekly, there are 2 types of posts students will have to make, the first is the weekly check-in. For a weekly check-in every student will have to answer these 3 questions in a post; with each answer being <100 words.

    1. What did you do this week?
    2. What is coming up next?
    3. Did you get stuck anywhere?

The second post is a blog post, here a student will be required to go into some detail on what they are working on, what they struggle with, and what solutions they have come to. There is no formal structure to this and every student is welcome to use their own style but the above three questions should be answered in the blog post at some point. 

email templates are in /gsoc/templates/email

**Comment by terriko** [comment]
I think the winning strategy here is to explain *why* we do the blog posts.  This has reduced the questions we get from the mentors. I'll update the templates, but here's more or less what I preface the whole thing with when I explain it to the mentors:

Students are required to blog for two reasons: firstly, to help the org admins tell that you're still active and on track, and secondly to help the wider python community understand what our students are doing.
