### ISSUE TITLE
GSoC 2019 - Create calendar page element

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#38]
This task is to make a template tag item that will display the calendar in the local time of the user. There are 2 examples below, you would need to support the entire list of timezones. 

GMT -7 MST example
```HTML
<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uhambjin8qdb9af4vt03c4djg4%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FDenver" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

GMT -8 PST example
```HTML
<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uhambjin8qdb9af4vt03c4djg4%40group.calendar.google.com&amp;color=%23853104&amp;ctz=America%2FLos_Angeles" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

Basically just need to change the value of "ctz="

to get and set the timezone see [https://docs.djangoproject.com/en/2.1/topics/i18n/timezones/](https://docs.djangoproject.com/en/2.1/topics/i18n/timezones/)

**Comment by Saurabh-Singh-00** [comment]
So, it should be something like this?

`
{% load ctz %}

<iframe **src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uhambjin8qdb9af4vt03c4djg4%40group.calendar.google.com&amp;color=%23853104&amp;ctz="*{% ctz %}*" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

**Comment by Saurabh-Singh-00** [comment]
So it should be something like? :- 
**{% load ctz %}**

`<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showPrint=0&amp;showCalendars=0&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=uhambjin8qdb9af4vt03c4djg4%40group.calendar.google.com&amp;color=%23853104&amp;ctz=`**{% ctz %}**`" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`

**Comment by botanicvelious** [comment]
Exactly!

**Comment by Saurabh-Singh-00** [comment]
Working on this issue.

**Comment by MastersAbh** [comment]
So, the user shouldn't be provided with the option to give anything as input ?
Instead, we need to form a logic to detect and display in his/her timezone?

**Comment by botanicvelious** [comment]
That is correct, the users timezone should be auto detected

**Comment by Saurabh-Singh-00** [comment]
> So, the user shouldn't be provided with the option to give anything as input ?
> Instead, we need to form a logic to detect and display in his/her timezone?

That would be too easy option to go with. Then we only need a drop-down to select timezones.

**Comment by botanicvelious** [comment]
We do not want the user to have to select the timezone, it should be automatic.
