### ISSUE TITLE
comments are getting spammed, 

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#386]
https://blogs.python-gsoc.org/en/admin/gsoc/comment/ is the page.

1. make comments page links to the articles
2. we need a better anti spam, we used recaptcha 3 last time but doesnt seem to work that well... maby try a recaptcha 2 box? or some custom captcha?

**Comment by terriko** [comment]
Maybe limit to logged in users and nuke the captcha.
