### ISSUE TITLE
GSoC 2019 - new person error

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#39]
Adding a new person (not user) throws an error

This is likely an error from a dependent package, may need to push a fix upstream.

```

Request Method: | POST
-- | --
http://127.0.0.1:8000/en/cms_wizard/create/
2.1.7
TypeError
render() got an unexpected keyword argument 'renderer'
C:\Python36\lib\site-packages\django\forms\boundfield.py in as_widget, line 93
C:\Python36\python.exe
3.6.8
['D:\\development\\python-blog\\python-blogs',  'C:\\Python36\\python36.zip',  'C:\\Python36\\DLLs',  'C:\\Python36\\lib',  'C:\\Python36',  'C:\\Python36\\lib\\site-packages']
Thu, 14 Feb 2019 22:50:30 -0800

[14/Feb/2019 23:49:37] "GET /en/cms_wizard/create/?page=21&language=en&edit&cms_path=/en/test/test123/ HTTP/1.1" 200 13648
Internal Server Error: /en/cms_wizard/create/
Traceback (most recent call last):
  File "C:\Python36\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 156, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Python36\lib\site-packages\django\core\handlers\base.py", line 154, in _get_response
    response = response.render()
  File "C:\Python36\lib\site-packages\django\template\response.py", line 106, in render
    self.content = self.rendered_content
  File "C:\Python36\lib\site-packages\django\template\response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "C:\Python36\lib\site-packages\django\template\backends\django.py", line 61, in render
    return self.template.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 171, in render
    return self._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 150, in render
    return compiled_parent._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 62, in render
    result = block.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\loader_tags.py", line 188, in render
    return template.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 173, in render
    return self._render(context)
  File "C:\Python36\lib\site-packages\django\test\utils.py", line 96, in instrumented_test_render
    return self.nodelist.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 937, in render
    bit = node.render_annotated(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\defaulttags.py", line 209, in render
    nodelist.append(node.render_annotated(context))
  File "C:\Python36\lib\site-packages\django\template\base.py", line 904, in render_annotated
    return self.render(context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 993, in render
    return render_value_in_context(output, context)
  File "C:\Python36\lib\site-packages\django\template\base.py", line 972, in render_value_in_context
    value = str(value)
  File "C:\Python36\lib\site-packages\django\utils\html.py", line 397, in <lambda>
    klass.__str__ = lambda self: mark_safe(klass_str(self))
  File "C:\Python36\lib\site-packages\django\forms\boundfield.py", line 33, in __str__
    return self.as_widget()
  File "C:\Python36\lib\site-packages\django\forms\boundfield.py", line 93, in as_widget
    renderer=self.form.renderer,
TypeError: render() got an unexpected keyword argument 'renderer'
[14/Feb/2019 23:50:31] "POST /en/cms_wizard/create/ HTTP/1.1" 500 291959
```

**Comment by ujjwalll** [comment]
I think we need to set renderer param in widget.py file as None in this case. It was the issue caused due to upgrading the Django. we need to go to the source where django is installed, go to widget.py file and update the renderer argument.

**Comment by ujjwalll** [comment]
Can you please upload a virtual environment of this blog so that I can make the changes accordingly.

**Comment by botanicvelious** [comment]
The current code has everything you need. Just create new person and you will see the error.

**Comment by sharmaadityaHQ** [comment]
Hey @botanicvelious  I am able to build the project. I encountered the same error on creating a new person.Could you please guide me on how to start with this issue.

**Comment by botanicvelious** [comment]
Would have to look at the stack trace and try to look at the code of the dependent modules etc and figure out where that error is coming from. It is likely an issue in a template in aldryn-newsblog if I was to guess. So find what template or otherwise is causing the error and fix it 👍  If you need help you can hit me up on irc, my irc is botanic on freenode in the #python-gsoc channel.

**Comment by sounak98** [comment]
@botanicvelious I could add a new person using the admin panel. When does this error exactly occur?

**Comment by botanicvelious** [comment]
you click create then "new person" not a new user. did you try a user?

**Comment by sounak98** [comment]
> you click create then "new person" not a new user. did you try a user?

No, I added a person. Here is a screenshot after adding the person.

![screenshot 2019-02-24 at 11 29 36 am](https://user-images.githubusercontent.com/22390515/53295722-8d7a6700-3827-11e9-89c0-908d69ccef22.png)

**Comment by botanicvelious** [comment]
Thats super odd can you paste your pip freeze and python ver?

Mine is 

```
Python v3.6.8

D:\development\python-blog\tese1>pip freeze
aldryn-apphooks-config==0.5.2
aldryn-boilerplates==0.8.0
aldryn-categories==1.2.0
aldryn-common==1.0.5
aldryn-newsblog==2.2.1
aldryn-people==2.2.0
aldryn-translation-tools==0.3.0
Babel==2.6.0
backport-collections==0.1
cmsplugin-filer==1.1.3
Django==2.1.7
django-appconf==1.0.2
django-appdata==0.2.1
django-classy-tags==0.8.0
django-cms==3.6.0
django-debug-toolbar==1.11
django-filer==1.4.4
django-formtools==2.1
django-js-asset==1.2.1
django-meta==1.4.1
django-meta-mixin==0.3.0
django-mptt==0.9.1
django-parler==1.9.2
django-phonenumber-field==1.3.0
django-polymorphic==2.0.3
django-reset-migrations==0.3.1
django-sekizai==0.10.0
django-sortedm2m==1.5.0
django-taggit==0.23.0
django-taggit-autosuggest==0.3.4
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-apphook-setup==0.3.0
djangocms-attributes-field==1.0.0
djangocms-audio==1.1.0
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-history==1.0.0
djangocms-link==2.3.1
djangocms-picture==2.1.3
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-video==2.1.1
easy-thumbnails==2.6
html5lib==1.0.1
lxml==4.3.1
phonenumbers==8.10.5
phonenumberslite==8.10.5
Pillow==5.4.1
python-dateutil==2.8.0
python-slugify==2.0.1
pytz==2018.9
six==1.12.0
sqlparse==0.2.4
tzlocal==1.5.1
Unidecode==1.0.23
webencodings==0.5.1
YURL==0.13
```

**Comment by ujjwalll** [comment]
In my pc it is also working, the reason for this error is a widget.py file in Django module. If you are using Django 2.0.8 or something like that, it will work, but for the Django version 2.1 and above, we need to configure the widget.py file and set renderer = Null, then it starts working as in my case. I have configured my widget.py file and it starts working fine. I think @sounak98 is using some different Django version.

**Comment by sounak98** [comment]
`Python 3.6.5` and `pip freeze` gives

```
aldryn-apphooks-config==0.5.2
aldryn-boilerplates==0.8.0
aldryn-categories==1.2.0
aldryn-common==1.0.5
aldryn-newsblog==2.2.1
aldryn-people==2.2.0
aldryn-translation-tools==0.3.0
appnope==0.1.0
Babel==2.6.0
backcall==0.1.0
backport-collections==0.1
bottom==2.1.3
cmsplugin-filer==1.1.3
decorator==4.3.2
Django==2.1.7
django-appconf==1.0.2
django-appdata==0.2.1
django-classy-tags==0.8.0
django-cms==3.6.0
django-debug-toolbar==1.11
django-filer==1.4.4
django-formtools==2.1
django-js-asset==1.2.1
django-meta==1.4.1
django-meta-mixin==0.3.0
django-mptt==0.9.1
django-parler==1.9.2
django-phonenumber-field==1.3.0
django-polymorphic==2.0.3
django-sekizai==0.10.0
django-sortedm2m==1.5.0
django-subcommand2==0.1.1
django-taggit==0.23.0
django-taggit-autosuggest==0.3.4
django-taggit-templatetags==0.2.5
django-templatetag-sugar==1.0
django-treebeard==4.3
djangocms-admin-style==1.2.9
djangocms-apphook-setup==0.3.0
djangocms-attributes-field==1.0.0
djangocms-audio==1.1.0
djangocms-blog==0.9.8
djangocms-column==1.9.0
djangocms-file==2.2.0
djangocms-googlemap==1.2.0
djangocms-history==1.0.0
djangocms-link==2.3.1
djangocms-picture==2.1.3
djangocms-snippet==2.1.0
djangocms-style==2.1.0
djangocms-text-ckeditor==3.7.0
djangocms-video==2.1.1
easy-thumbnails==2.6
FredIRC==0.3.0
html5lib==1.0.1
ipython==7.2.0
ipython-genutils==0.2.0
jedi==0.13.2
lxml==4.3.1
parso==0.3.4
pexpect==4.6.0
phonenumbers==8.10.5
phonenumberslite==8.10.5
pickleshare==0.7.5
Pillow==5.4.1
prompt-toolkit==2.0.8
ptyprocess==0.6.0
Pygments==2.3.1
pyrcb2==0.5.3
python-dateutil==2.8.0
python-slugify==2.0.1
pytz==2018.9
six==1.12.0
sqlparse==0.2.4
traitlets==4.3.2
tzlocal==1.5.1
Unidecode==1.0.23
wcwidth==0.1.7
webencodings==0.5.1
YURL==0.13
```

@ujjwalll even I am using django 2.1.7

**Comment by botanicvelious** [comment]
@sounak98 so it looks like with those packages i still get the error on my system, did you add them via "Home › Aldryn_People › People › Add Person" or from the top bar "create" button?

**Comment by sounak98** [comment]
@botanicvelious yes. I also tried it on a fresh install. I could still create a new `Person`.

Are you all on Windows?

**Comment by ujjwalll** [comment]
Nope, I am on mac @sounak98 , also tried my thing on Linux installed in my desktop. Same widget.py file configuration and things started working.

**Comment by botanicvelious** [comment]
@sounak98 that is really odd because in 2.1

>Support for Widget.render() methods without the renderer argument is removed.

Which is the cause of this error message, if i drop the version to 2.0.8 it works

**Comment by ujjwalll** [comment]
Yes, I am saying the same thing that we should configure our widget.py file in the Django and set that renderer to Null at line number 93 I guess. With the update of Django, they created a new argument renderer which should be set to null. SO, either sir @botanicvelious should configure their widget.py file,
we should drop down our Django version or the best case is to attach the virtual environment to this repo with the configured widget.py file so that everyone is on the same page.

**Comment by botanicvelious** [comment]
@sounak98 this is what i see

[https://filebin.net/olwr2223tng362wv/Untitled.png?t=g575o95g](https://filebin.net/olwr2223tng362wv/Untitled.png?t=g575o95g)

That is the error I get after selecting "new person" from the circled button.

**Comment by sounak98** [comment]
Very weird. I'll try to figure out what's happening.

**Comment by botanicvelious** [comment]
> 
> 
> Yes, I am saying the same thing that we should configure our widget.py file in the Django and set that renderer to Null at line number 93 I guess. With the update of Django, they created a new argument renderer which should be set to null. SO, either sir @botanicvelious should configure their widget.py file,
> we should drop down our Django version or the best case is to attach the virtual environment to this repo with the configured widget.py file so that everyone is on the same page.

We can't drop the django version as that breaks other things, also that's not really a solution. I would say identify where the problem is coming from then we can figure out the best solution.

**Comment by sharmaadityaHQ** [comment]
@botanicvelious  i am getting the same error as shared by you https://filebin.net/olwr2223tng362wv/Untitled.png?t=g575o95g here. I am running on ubuntu linux.

**Comment by botanicvelious** [comment]
> 
> 
> Very weird. I'll try to figure out what's happening.

@sounak98 when you run with runserver check and make sure that your django version is correct, maby there is something wierd on your side. Should say the following.

```
System check identified 16 issues (0 silenced).
February 23, 2019 - 23:53:45
Django version 2.1.7, using settings 'gsoc.settings'
```

**Comment by botanicvelious** [comment]
@sharmaaditya570191 looks to be a problem with @sounak98 probably some version issue or something

**Comment by ujjwalll** [comment]
Okay, I will try my best to find an appropriate solution.

**Comment by sounak98** [comment]
```
System check identified 16 issues (0 silenced).
February 23, 2019 - 22:34:59
Django version 2.1.7, using settings 'gsoc.settings'
```

@botanicvelious it's the same version `2.1.7`. Even a fresh install of all the dependencies didn't change anything. Adding a person still works.

**Comment by botanicvelious** [comment]
Super odd, not sure why it works for you but no-one else @sounak98 

Looks like some other people are looking into this issue anyways so maybe when they find the issue we can figure out how it happens to work for you. 

Side note: have you tried a clean git clone? Maby its something with your database?

**Comment by sounak98** [comment]
Yeah I have tried a clean git clone too.

> Looks like some other people are looking into this issue anyways so maybe when they find the issue we can figure out how it happens to work for you.

Yeah then we will be able to gain more insight about what might have happened in my setup.

**Comment by rajgoesout** [comment]
@botanicvelious This looks like an upstream issue in django-cms. They have used .render() without the renderer argument. See: https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer

**Comment by botanicvelious** [comment]
we can push a fix upstream to them :)

**Comment by botanicvelious** [comment]
not needed anymore
