### ISSUE TITLE
Image Resizing while writing blogs doesn't work

### ISSUE THREAD

**Issue by Nibba2018** [python-gsoc/python-blogs#394]
**Describe the bug**
Hello devs, the resizing of a high-resolution image doesn't work as expected.

**To Reproduce**
While writing blogs:
* Insert this image:
![fury-logo](https://python-gsoc.org/logos/FURY.png)
* Change the width/height to any value lets say "100"
* The size of the Image doesn't change after the blog is saved.

**Expected behavior**
It is expected to have the specified resolution but it keeps its the original one.

**Desktop (please complete the following information):**
 - OS: Pop!_OS (20.04) (Ubuntu based distro)
 - Browser: Firefox
 - Version: 76.0.1

**Comment by botanicvelious** [comment]
Seems that ckeditor source is correct but the width and height arent being saved to the database, thanks for the report

**Comment by sharmaadityaHQ** [comment]
I have also experienced the same problem.

**Comment by McSinyx** [comment]
Has this been fixed?  I think [it works for me](https://blogs.python-gsoc.org/en/mcsinyxs-blog/unexpected-things-when-you-re-expecting/) [setting the size in CSS](https://gist.github.com/McSinyx/4624ab7af8b36d45bc3bf5612e6a6504#file-blog20200609-html-L76-L77).

**Comment by Nibba2018** [comment]
@McSinyx , That sounds like a good workaround. But to my knowledge, I don't think it's fixed yet.
