### ISSUE TITLE
make pypi package

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#395]
this would be nice

**Comment by Mrinank-Bhowmick** [comment]
@botanicvelious 
Hey I am interested to solve this issue ,can you please provide some more details and how to approach this.

**Comment by Ranit-Bandyopadhyay** [comment]
I am interested to solve this issue. can you please provide some more details and how to approach this.

**Comment by terriko** [comment]
Closing in preparation for archiving this repo.
