### ISSUE TITLE
html tags

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#396]
`<tt>` and `<article>` both dont work, prolly should just strip all unknown tags... seems that they were encased in a code block tho

also `<meta charset="utf-8">` 

for example https://blogs.python-gsoc.org/en/dvijaywargiyas-blog/first-blog-gsoc-2020/

**Comment by botanicvelious** [comment]
Seems that google drive is what is causing the `<meta charset="utf-8">` to be inserted

**Comment by botanicvelious** [comment]
The tt tags are coming from using the typewriter style in the editor

![issue](https://i.imgur.com/GqgSPhF.png)

**Comment by arcriley** [comment]
Working on this
