### ISSUE TITLE
exception on used links

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#397]
Shouldnt throw an exception and send an email when

Blog Error at June 2, 2020, 5:16 a.m. Message: link already used

**Comment by arcriley** [comment]
When a user clicks the user verification link after they're already verified, they get a server crash. Fun!

**Comment by botanicvelious** [comment]
It sends an email because of the exception for example like below

Exception on runcron process_items

Blog Error at May 31, 2020, 8:39 p.m. Message: link already used

**Comment by botanicvelious** [comment]
fixed
