### ISSUE TITLE
GSoC 2019 - Create scheduler build_items page

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#40]
This issue is to create a page and system that allows you to select tasks to be scheduled at specific times and on specific triggers.

For date scheduling you would select a date and time, then you would select the task, the tasks would need to come from the scheduler.command model field choices as a selectbox. When build_items is run it would check this data and see if it needs to add something to the schedule model data table.

For trigger schedule, you would need to write the base code to be able to specify some logic, for example. 
>foreach user where group == student if last_blog_post > 7 days then send_email for user

That is the only trigger scheduler you need to add for now but it needs to be simple to add more. These triggers may best be done in python code and not as part of the webpage.

This system would need to be tied into the build_items part of the scheduler system, so when build_items is run it auto adds to the scheduler model data table the items as appropriate.

**Comment by DeboDevelop** [comment]
What do you meant by "When build_items is run it would check this data and see if it needs to add something to the schedule model data table."

Also "These triggers may best be done in python code and not as part of the webpage."
You mean make a python script and refer that script from website?? Or do you mean create a separate django app? Or something else. 

Can I use Celery?

I want to work on the issue.

**Comment by botanicvelious** [comment]
The file https://github.com/python-gsoc/python-blogs/blob/master/gsoc/management/commands/runcron.py is what implements the build_items command. You would expand that to add scheduler items based on the items scheduled to be triggered.

**Comment by DeboDevelop** [comment]
Okay. Thanks a lot.
I get it now.

I will start working on it.

**Comment by im029** [comment]
Is there any update on this? if not, can I start working on this?
@DeboDevelop @botanicvelious

**Comment by DeboDevelop** [comment]
@im029 I am still working on this. I am sorry man.

**Comment by botanicvelious** [comment]
@im029 There are some other issues open you could look at.

**Comment by sounak98** [comment]
@botanicvelious  the date scheduler is not necessary anymore because I had added an `activation_date` field on the `Scheduler` model itself.

**Comment by botanicvelious** [comment]
still needs to be added to the page so that it works, makes it easier tho :)

**Comment by DeboDevelop** [comment]
I am really sorry. I am overloaded with work and I not getting any time to complete this work.

I think somebody else should work on the issue. 

I am really sorry for wasting everybody's time.

If you guys want to work on this issue, you can. I am not getting time and I don't want your progress get stagnated because of me.
