### ISSUE TITLE
deleting userprofile when matches

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#403]
when all items match and you delete a userprofile it nukes all of the ones that are the exact same

**Comment by diwash007** [comment]
@botanicvelious Can you please elaborate on this issue?
How can all items of user profiles match? That will throw a CONSTRAINT error if you try to create profiles with the same info.

**Comment by botanicvelious** [comment]
You can create the same user profile at least where it is blank, I believe you can also do it with non blank ones as well so i think the constraint isnt working

**Comment by botanicvelious** [comment]
So I just checked the constraint doesn't work when the sub-org is blank apparently. If you set role other and the sub-org to be - then there can be multiple instances.

So this issue is fixing the constraint, as well as fixing the deleting of user profiles from the users page so that only one is removed.
