### ISSUE TITLE
remove sqllite db

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#408]
We should remove the sqllite db while also proving default data

https://docs.djangoproject.com/en/3.0/howto/initial-data/

**Comment by botanicvelious** [comment]
https://docs.djangoproject.com/en/3.0/howto/initial-data/

**Comment by lothemar** [comment]
@botanicvelious what default data are you interested in putting? What's the motivation behind removing the sqlite db?
