### ISSUE TITLE
GSoC 2019 - Add features to rich text editor

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#41]
The wysisyg editor is missing a few important features

1. Image support, this would need to allow users to add images to the blog post

would need to support the setting of width and height

[https://ckeditor.com/cke4/addon/image2](https://ckeditor.com/cke4/addon/image2) may be helpful

2. youtube support, need to be able to add a youtube video by adding the video url, for example

>https://youtu.be/KjelB1bCBzU

would be converted to 

```html
<iframe width="560" height="315" src="https://www.youtube-nocookie.com/embed/KjelB1bCBzU" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
```

Also would need to be able to specify the width and height

[https://ckeditor.com/cke4/addon/youtube](https://ckeditor.com/cke4/addon/youtube) may be helpful

Also i found [https://www.diehlworks.com/en/blog/customize-ckeditor-in-django-cms/](https://www.diehlworks.com/en/blog/customize-ckeditor-in-django-cms/)

**Comment by sounak98** [comment]
@botanicvelious `ckeditor` and `djangocms-text-ckeditor` gives weird errors! Even pre-built sources from the official website are buggy.

```
TypeError: undefined is not an object (evaluating 'a.lang.about.title')
```

**Comment by botanicvelious** [comment]
Where were you seeing that error?

**Comment by sounak98** [comment]
The error exactly happens when I place a pre-built `ckeditor` source in the path `gsoc/static/djangocms_text_ckeditor/`. Otherwise it runs fine (the older one).

**Comment by botanicvelious** [comment]
Ah I see, the issue is that the cms ckeditor is partly custom so you need to use the version from 
>C:\Python36\Lib\site-packages\djangocms_text_ckeditor\static\djangocms_text_ckeditor

You cant just use the original ckeditor version from the site

Did you check the guide at [https://www.diehlworks.com/en/blog/customize-ckeditor-in-django-cms/](https://www.diehlworks.com/en/blog/customize-ckeditor-in-django-cms/)?

**Comment by botanicvelious** [comment]
Also a side note, the django cms plugin uses CKEditor 4.7.3 the latest version is 4.11.1 so there may be some issues with that as well.

**Comment by sounak98** [comment]
@botanicvelious the guide says:

> First, download a custom configured version of CKEditor (one that includes the specific feature plugins desired). I recommend using their builder which makes selection of plugins, skin, and languages extremely easy.
>
> The downloaded custom CKEditor needs to be placed in the project's root static folder as shown below

There are some compatibility issues with `4.7.3` with the different plugins (Youtube and Enhanced image) because the API has been updated to add the function `editor.plugins.detectConflict` after 4.7.3. I'm not being able to find the correct version of the Youtube plugin for `4.7.3`.

That's why I was trying to go for the latest version.

**Comment by botanicvelious** [comment]
Well you could try building the latest version using the instructions at [https://github.com/divio/djangocms-text-ckeditor](https://github.com/divio/djangocms-text-ckeditor) or the other option I can think of would be to try an older version of the youtube plugin from [https://github.com/fonini/ckeditor-youtube-plugin/](https://github.com/fonini/ckeditor-youtube-plugin/) it looks like each release is tagged so that may also be a easy way to deal with it. Looks like [https://github.com/fonini/ckeditor-youtube-plugin/commits/v2.1.4](https://github.com/fonini/ckeditor-youtube-plugin/commits/v2.1.4) should be old enough, there may be a newer release that will also work tho.

I would try building the latest ckeditor if possible, if not then just use the older youtube plugin

**Comment by sounak98** [comment]
Yeah I was also trying to use the latest version of ckeditor. 

Also I tried to look for an older version of Youtube, but their changelogs doesn't mention anything useful. The other plugins are versioned according to the ckeditor version. This is not, mostly because it is not maintained by the ckeditor community.

I'll try once with 2.1.4 but before that let me see if I can get the latest version of ckeditor integrated with djangocms-text-ckeditor.

**Comment by botanicvelious** [comment]
I really have no idea which version of the youtube plugin will work I just picked one that was tagged before the release of 4.7.3

**Comment by sounak98** [comment]
That's a good idea, I was trying to look through the changelogs. I'll see if it works.
