### ISSUE TITLE
gdpr compliance

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#410]
Need to make sure we up on this

**Comment by terriko** [comment]
I've emailed the website mailing list, we'll see if anyone has an answer about what the PSF's best practices are on this front.

Currently the privacy policy appears to predate GDPR.

**Comment by terriko** [comment]
Response from the email was that we don't currently have a gdpr policy and there's no ETA on that happening, so we'll close this for now as we can't really do anything meaningful without a gdpr policy.
