### ISSUE TITLE
Feature request: Check if any users registered in the blogs are nto yet registered in Google's system

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#416]
We'd like to be able to see if any invites are missing.  It's a pain to log in to Google programmatically, but we might be able to take a .csv export of the currently registered mentors and compare it against the mentors registered in our system and see who's not gotten an invite yet.

**Comment by botanicvelious** [comment]
This does not seem to be possible anymore with the new system so I will close it.
