### ISSUE TITLE
Requirements for lists of mentors/students

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#419]
### Mentor list (for org admins/sub-org admins):
- name
- email 
- sub-org(s)
- alternate contact methods (irc, phone, etc.) (maybe click to profile for this because of width limits)
- do they have an invite to google's system or not?

This list should be current year only by default, with maybe an option to see previous year's list if you're an org admin.

**Things org admins might want to modify with mentors**: 
- add/subtract sub-orgs (maybe not necessary if we fix the bug around this)
- tick the tickybox when they get an invite (solved)

**Things org admins want**: 
- get list of emails for all mentors per sub org (for emails not sent through the system) 
- get list of emails for all mentors (for syncing with mailman) -- currently getting that from teh google csv export.

### Student list (for mentors/sub-org admins)
- name
- email (maybe not needed)
- sub-org
- blogging compliance status (e.g. are they late on any blog posts?  have they already posted the one for this week?)
- link directly to blog

Again, current year only by default, option to see previous year's lists.

Right now this completely doesn't exist, so we'd need to make sure all mentors have access to this.

**Comment by terriko** [comment]
pinging @arcriley -- this is my last wishlist item, if you get to it.  (should be easy for us to do after gsoc if you don't, though)

**Comment by Rashika101** [comment]
Do you still interested in new contributors? If yes, I would like to contribute in this repository issue......Will u explain me a little more?

**Comment by botanicvelious** [comment]
the PSF is accepting at most one student this year, as such we recommend applying to other sub-organizations. You can find the other organizations on the [Project Ideas](https://python-gsoc.org/ideas.html) page. If you are still interested we will only be accepting a student who already has a knowledge of Django and Python.

As for this issue this is a fairly long  list, if you wish to work on it please message botanic on #python-gsoc on the @freenode irc channel

**Comment by chandan00761** [comment]
@botanicvelious I have implemented some of the features using techniques described below:

**Features Implemented**

- [x] Show Details of mentors, sub-admins, students of a Suborg to the suborg admins.
- [x] View details of mentors, sub-admins, students of current year by default.

Steps taken:

1. Created a new group "suborg_admin" from admin dashboard. All the UserProfiles with role suborg admin will be assigned to the group and made staff. (maybe run a query using manage.py shell to apply to all existing users)
2. "suborg_admin" group will have permission "gsoc | user profile | Can view user profile" permission.
3. Upon logging to admin dashboard, suborg admin will see a page like this.

![image](https://user-images.githubusercontent.com/28469311/144062615-8edb1402-5a8f-47c8-a927-79290215a111.png)
 
Here they can filter the data according to their choice.
