### ISSUE TITLE
Not denoted code to enclose it in backticks (`).

### ISSUE THREAD

**Issue by Aju100** [python-gsoc/python-blogs#423]
Hello opensource contributor,

I am a new open-source contributor and willing to contribute to the python software foundation. After reading out the [python-blogs](https://github.com/python-gsoc/python-blogs) documentation, there are few minor mistakes of not denoting code to enclose it in backticks.
![notdenoted](https://user-images.githubusercontent.com/29862610/102707654-d89a1f80-42c2-11eb-80d9-769020bf3fc9.png)

It will be great if those minor issues are fixed.

**Comment by PawelBorkar** [comment]
Hi Aju,
I would love to work on this issue.
