### ISSUE TITLE
Bug: Unable to migrate database

### ISSUE THREAD

**Issue by Aju100** [python-gsoc/python-blogs#425]
**Unable to migrate database**
After successfully cloning the whole project, I had installed the requirements dependencies. But for migrating the database, there is a mismatch of the foreign keys.

**To Reproduce**
1. Clone the python-blogs
2. pip install -r requirements.txt (Make sure you make the new virtual environment and activated using virtualenv)
3. python manage.py makemigrations
4. python manage.py migrate
5. See errors 

**Expected behavior**
Whole DB models should successfully be migrated to the Sqlite3 database.

**Screenshots**
![djangomismatch](https://user-images.githubusercontent.com/29862610/102708433-1ac65f80-42c9-11eb-99a3-55a08d3130c3.png)

**Comment by Aju100** [comment]
With the rise of this bug, we can't able to perform Testing too. 
![test](https://user-images.githubusercontent.com/29862610/102991844-0d66da80-4540-11eb-8524-815e393d3999.png)

**Comment by Aju100** [comment]
Hi @terriko I would love to know about what issues are going on while running it in my machine ???

**Comment by arcriley** [comment]
Use mariadb, not sqlite.

**Comment by Aju100** [comment]
@arcriley  thank u. But I wanted to know why it's not working on sqlite3? I think the problem is in Django model, correct me if I am wrong.

**Comment by terriko** [comment]
@Aju100 we don't have any intention of supporting sqlite for this project.  If you figure it out, feel free to let us know, but I wouldn't spend too much time on it.  I'm going to close this bug as sqlite is unsupported.

**Comment by Aju100** [comment]
sure @terriko  what I need to solve is to run and migrate on the required database model and being able to run this project, may I know how can I properly migrate on MySQL or PostgreSQL?

**Comment by terriko** [comment]
@Aju100 As far as i know, none of the developers have ever done that, so it's unlikely anyone here will be able to help you.  Sorry!

And with my GSoC org admin hat on: If you're looking for a potential GSoC project, I suggest you try [MNE-Python](https://github.com/mne-tools/mne-python/wiki/GSoC-Ideas#project-ideas) and [Fury](https://github.com/fury-gl/fury/wiki/Google-Summer-of-Code-2021) both of whom already have ideas pages up and are more prepared for helping students right now.
