### ISSUE TITLE
Remove extraneous questions from sub-org form

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#426]
**Describe the bug**
The sub-org form is too long and annoying to fill out, and asks for things that we aren't actually using anywhere.

**Expected behavior**
We don't really need to know the answers to the following questions:

1. Has your org been accepted as a mentor org before?
2. What years did you participate in gsoc?
3. was this as a suborg
4. if your org has applied but not been selected...

I think these were taken from the main gsoc form, but we don't really take any of that into account as part of our selection process (and if they participated with us, we generally already know)

We don't *really* need to know "what year was the project started" either, but it's at least useful for helping us quickly tell if a project may be a bit too new to have the mentor support required.

**Comment by ayushranjantiwari** [comment]
Hlw ma'am. I would like to work on the project.
