### ISSUE TITLE
reglink error message

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#430]
When a reglink is already used it should throw a error message not a 500, also should give a message when registration is completed for a existing account

**Comment by diwash007** [comment]
Looks like this issue has already been fixed. Registration errors and registration completion messages are working fine.

**Comment by botanicvelious** [comment]
When a link has already been used, but the link is clicked again it throws a 500, not an error page.

**Comment by diwash007** [comment]
![image](https://user-images.githubusercontent.com/39879720/142764464-e49f3084-8f9c-4d65-bf0d-2c191826dd08.png)
It is throwing this error if I reopen the link after creating the account.

**Comment by botanicvelious** [comment]
Were you already logged in as a user?

**Comment by diwash007** [comment]
yes that was when I was logged in .. but without being logged on, it throws this: 
![image](https://user-images.githubusercontent.com/39879720/145356750-f3eff237-47f5-4da2-9af0-db7fc00b669e.png)

**Comment by botanicvelious** [comment]
Issue has been fixed, now it throws a message when a link that has already been used rather then an server 500 error
