### ISSUE TITLE
let users change info

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#432]
users should be able to update there email address etc

**Comment by YSSVR** [comment]
hello @botanicvelious. I am new to open source so please help me to start with. you made me feel easy about my starting point by narrowly saying the thing, first of all, Thanks. And please elaborate on the task to be done.

**Comment by botanicvelious** [comment]
the PSF is accepting at most one student this year, as such we recommend applying to other sub-organizations. You can find the other organizations on the [Project Ideas](https://python-gsoc.org/ideas.html) page. If you are still interested we will only be accepting a student who already has a knowledge of Django and Python.

As for this issue there needs to be a box added to the "my profile" menu item that allows a user to update there email address.

**Comment by iaryangoyal** [comment]
hello I have knowledge of python and Django both can you help me

**Comment by botanicvelious** [comment]
You can find the information on working with the PSF at https://python-gsoc.org/psf_ideas.html
