### ISSUE TITLE
changing email breaks suborg applications

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#433]
https://github.com/python-gsoc/python-blogs/blob/master/suborg/views.py#L32

That needs to key off the users that are set to suborg admins, also it looks like users submitting applications are not given the userprofile suborg admin...

**Comment by botanicvelious** [comment]
looks like its adding "other" profiles

**Comment by tusharbhadak** [comment]
Hi @botanicvelious, I'd love to solve this issue. Currently I pursue my career as an Intern ML Engineer and I'm student of MSc ICT. I believe that the skills that I've attained from dynamic environment defines me and I'm looking forward to implementing and polishing them in any opportunity that I receive.

**Comment by botanicvelious** [comment]
@tusharbhadak if you are interested in working with the PSF for GSoC 2021 please contact me on the irc channel #python-gsoc on freenode just ask for botanic

The PSF ideas page is located at https://python-gsoc.org/psf_ideas.html with additional information as well
