### ISSUE TITLE
Unable to make new articles

### ISSUE THREAD

**Issue by imsahil007** [python-gsoc/python-blogs#437]
**I have been unable to post new articles for quite some time now.**
 The page randomly gives me the error-  Article has no owner.
![image](https://user-images.githubusercontent.com/35963992/126533815-252c1099-5d3a-4934-a73d-1d62dc705c2d.png)

Let me know If I am doing something wrong

Steps:
1. Login into your account and go to Article list
2. Click on Add Article Button.
3. It will give you a drop-down menu with a list of all python-gsoc users. You are not able to post on someone else's account. So, we should remove the choice.
4. If you click on News & Blog or your own username's blog option- you will be able to reproduce the above previewed error.

**Comment by botanicvelious** [comment]
We should remove that menu item, to post click create on the right at the
top of the menu, dont go into the article list.

**Comment by Anushakhalil** [comment]
@botanicvelious  Hey, I want to contribute to this issue. Can you guide me?

**Comment by botanicvelious** [comment]
@Anushakhalil for this you will have to setup the blogs system and then remove the menu item referenced above.
