### ISSUE TITLE
Cannot access my sub org section

### ISSUE THREAD

**Issue by krishnakatyal** [python-gsoc/python-blogs#448]
**Describe the bug**

**To Reproduce**

1. Go to https://blogs.python-gsoc.org/en/suborg/application/
2. See error
<img width="1431" alt="Screenshot 2022-02-22 at 2 39 18 PM" src="https://user-images.githubusercontent.com/37455387/155105340-28bcdfb9-35b1-4fe4-9493-31fcf6ca1600.png">

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by botanicvelious** [comment]
What suborg are you with so I can check this?

**Comment by botanicvelious** [comment]
Fixed in commit 7beeb65a7b14ec492647d38827bf8b2bbfc60ad2

**Comment by krishnakatyal** [comment]
Thanks
