### ISSUE TITLE
cannot visit my sub org section

### ISSUE THREAD

**Issue by krishnakatyal** [python-gsoc/python-blogs#451]
**Describe the bug**

**To Reproduce**
1. Go to '[...](https://blogs.python-gsoc.org/en/)'
2. Click on 'login'
3. forbidden (403)
CSRF verification failed. Request aborted.
Help
Reason given for failure:
    CSRF token missing or incorrect.
    
In general, this can occur when there is a genuine Cross Site Request Forgery, or when [Django’s CSRF mechanism](https://docs.djangoproject.com/en/3.2/ref/csrf/) has not been used correctly. For POST forms, you need to ensure:
Your browser is accepting cookies.
The view function passes a request to the template’s [render](https://docs.djangoproject.com/en/dev/topics/templates/#django.template.backends.base.Template.render) method.
In the template, there is a {% csrf_token %} template tag inside each POST form that targets an internal URL.
If you are not using CsrfViewMiddleware, then you must use csrf_protect on any views that use the csrf_token template tag, as well as those that accept the POST data.
The form has a valid CSRF token. After logging in in another browser tab or hitting the back button after a login, you may need to reload the page with the form, because the token is rotated after a login.
You’re seeing the help section of this page because you have DEBUG = True in your Django settings file. Change that to False, and only the initial error message will be displayed.
You can customize this page using the CSRF_FAILURE_VIEW setting.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by botanicvelious** [comment]
I cant reproduce it with eaither latest firefox or chrome

**Comment by botanicvelious** [comment]
Can you email me the username and the url that is throwing the error so I can try to reproduce it with your account, it could be account specific or something...

**Comment by diwash007** [comment]
I was able to reproduce it.
![image](https://user-images.githubusercontent.com/39879720/158614570-c80ea753-81bd-45df-956c-b4ea7096f900.png)
well there is no any problem at all ... just the debug on the production need to be set to false ... everything is working as expected
