### ISSUE TITLE
Users register directly onto the system creates blank profile

### ISSUE THREAD

**Issue by diwash007** [python-gsoc/python-blogs#457]
Users can register directly onto the system by inviting themselves from /accounts/new

1. Go to /accounts/new
2. Fill out the email and click the button
3. Signup from the link received in the email

**Expected behavior**
Users shouldn't be allowed to invite themselves. Only admins should have this power

**Desktop**
 - OS: any
 - Browser: any

**Comment by botanicvelious** [comment]
People being able to register is fine, the blank profile being created tho is not correct.
