### ISSUE TITLE
List of 2022 sub-org admins shows no entries

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#458]
**Describe the bug**
When I go to view the list of sub-org admins for 2022 from the useradmin page, none of the sub-org admins are showing.

**To Reproduce**
1. Go to user admin page
2. Click on "sub-org admins"
3. Look at the list of sub-org admins and note that none of them have 2022 next to their name.  I can see folk from 2021 and 2020.

**Expected behavior**
I should see the list of 12 or so folk who registered as sub-org admins.

**Desktop (please complete the following information):**
Chrome and Firefox on Linux.  (This bug is likely device-independent)

**Comment by botanicvelious** [comment]
Caused by #453
