### ISSUE TITLE
Feature request: CSV export of mentor + sub org admin info

### ISSUE THREAD

**Issue by terriko** [python-gsoc/python-blogs#459]
* related to #336 -- a fix to this issue would be good enough to also solve that one.

**Is your feature request related to a problem? Please describe.**
I periodically need to get a list of mentors for a given sub org, or a list of all mentors for the current calendar year.  It would be nice if I could export such a list so I could load it into Google Sheets and then cut/paste the emails I need into other applications.

Example use cases:
* A student has emailed saying that they haven't gotten any response from their sub-org.  I'd like to be able to reply to the student email and cc all the relevant mentors to make sure the connection is made.
* 2-3 times per year, I need to sync the mailing list with the list of registered users.  Mailman accepts a list of email addresses (one per line) for synchronization and will subscribe/unsubscribe people as needed, but I need that list of emails.
* I want to double-check that all sub-orgs have at least 3 mentors, so I want to see a list of all registered mentors and sub-org admins and sort them by sub-org to count them.

Currently, I cut from the https://blogs.python-gsoc.org/en/admin/gsoc/userprofile/ view and paste it into Google Sheets, which mostly works, but there's no way to see mentors+sub-org admins and not students in that view, so I have to do this twice.

**Describe the solution you'd like**
A button where I could export a list of all current mentors/sub-org admins with their names, emails, sub-orgs and user type (mentor or sub-org admin) listed.  Or a view showing those things so I could cut/paste.

**Comment by botanicvelious** [comment]
Adding a sort for mentor+suborg admin should resolve this.
