### ISSUE TITLE
GSoC 2019 - Add field for uploading accepted proposal to student account

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#46]
This issue is for creating an upload button that would add an accepted student proposal to the student's user account. The button would have to take a pdf file as an upload, as well as would have to prompt the uploader to be sure that they removed all private data before uploading. Bonus points if you actually scan the pdf text looking for items such as emails, phone numbers, etc and prompt the user to be 100% sure if you find anything.

**Comment by ghost** [comment]
Can I work on it?

**Comment by ghost** [comment]
Should the uploader be the student or some other admin user like a mentor?

**Comment by botanicvelious** [comment]
go for it! as for who is uploading it would be the student themselves.

**Comment by ghost** [comment]
ok, will finish it as soon as I can.

**Comment by sounak98** [comment]
Was this not closed by https://github.com/python-gsoc/python-blogs/pull/48?

@botanicvelious @ntkomata
