### ISSUE TITLE
GSoC 2019 - Add upload to ckeditor image widget

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#49]
This task is to have a user to select a file as part of the ckeditor wysiwyg editor image insert button. This would need to auto upload the file to the server rather than ask to select a url.

Could also just convert the image to a source tag rather than uploading it, for example 

```HTML
<img src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=" width="0" height="0" alt="" />
```

Maybe easier than dealing with uploading files.

**Comment by im029** [comment]
@botanicvelious  I would like to work on this.

"we need to auto-upload files", does that mean we have to remove the current URL selection box and then add the file browser?

**Comment by botanicvelious** [comment]
Well the url would be fine if it fetched the image automatically. That way in case the image host goes away etc the blog posts dont break

**Comment by im029** [comment]
Gotcha. However, since we will be storing the images on the server we need to decide what to do when the associated post/page/blog is deleted.

**Comment by botanicvelious** [comment]
They wont be deleted, however if you store the image as part of the page text as a data:image then if it ever was deleted then the text in the page would also be deleted.

**Comment by ghost** [comment]
I'll work on this. Seems im029 hasn't started yet. :)
