### ISSUE TITLE
GSoC 2019 - Send email template

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#5]
This task is to add the ability to send an email based on templates.

You will need to create at least 2 basic templates and have the system able to be told which template to use and send an email to the specified address using that template.

Bonus points: Be able to specify data to replace in the templates for example "Name"

**Comment by ujjwalll** [comment]
Can I work on this issue?

**Comment by botanicvelious** [comment]
go for it!

**Comment by botanicvelious** [comment]
Also just so you know this would be used by the scheduler system, it is being worked on as part of pr #32 so its probably easiest to pull down the code in his pr and then just expand the 

```Python
def send_email(scheduler):
    return True
```

with the new code, you would return a true on a success, false on failure, along with the error message.

**Comment by ujjwalll** [comment]
I am creating a page in which one can select one email template and write the email address to which it is supposed to be delivered and then he can type the name and the mail will be sent to that person? I am creating this template through jinja templating.

**Comment by botanicvelious** [comment]
It shouldn't be a page, this would be for an automatic sending of an email, basically you would be passed something like

```JSON
{
  "to_email": "test@email.com",
  "template": "testemail.template",
  "from_email": "test@python-gsoc.org",
  "Subject": "test email!",
  "data": {
    "username": "test",
    "message": "this is a test message"
  }
}
```
to the send_email function that you are working on, then it would take that json and parse it to do the template filling in etc

**Comment by ujjwalll** [comment]
Okay, I got it, I am taking it in a template way, sorry for that, I will try to complete this.

**Comment by botanicvelious** [comment]
Just fyi pr #32 has been merged so you can just pull the latest code from the repo and go about editing the send_email function.

**Comment by ntkomata** [comment]
@ujjwalll Still working on this?

**Comment by ghost** [comment]
@botanicvelious I'd like to work on this since there is no update for a month

**Comment by botanicvelious** [comment]
@ntkomata go for it

**Comment by Saurabh-Singh-00** [comment]
> ```json
> {
>   "to_email": "test@email.com",
>   "template": "testemail.template",
>   "from_email": "test@python-gsoc.org",
>   "Subject": "test email!",
>   "data": {
>     "username": "test",
>     "message": "this is a test message"
>   }
> }
> ```
@botanicvelious  So the above json will be in scheduler.data field ?
![image](https://user-images.githubusercontent.com/36993159/55411119-ae4e7e80-5582-11e9-8822-356835303429.png)
Something like this?

**Comment by ghost** [comment]
@Saurabh-Singh-00 The message should be a django template string.
i'm working on this btw :)

**Comment by ghost** [comment]
@Saurabh-Singh-00  Uhh actually no. The message should just be a string since it's the template data. Sorry, I wasn't looking :)

**Comment by botanicvelious** [comment]
@ntkomata why wouldn't it be that? the data is how you would choose the template etc

**Comment by ghost** [comment]
@botanicvelious umm I'm saying the "data" in the data field :) it should be a json array with raw strings inside right?
And maybe it should be named "template_data"

**Comment by botanicvelious** [comment]
the data field could be data for the irc bot, or otherwise, it is the "data" for the "command"
