### ISSUE TITLE
GSoC 2019 - Hide admin only fields

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#50]
This task is to not allow non super user users when adding a blog post article to not be able to change the following.

- [ ] Author
- [ ] Date 
- [ ] Time
- [ ] Is featured
- [ ] Meta Options 
- [ ] Advanced Options
- [ ] Also pre-select is published

**Comment by ghost** [comment]
@botanicvelious I'd like to work on this one. :)

**Comment by botanicvelious** [comment]
go for it

**Comment by ghost** [comment]
https://github.com/ntkomata/python-blogs 
@botanicvelious 
I tried to add certain fields to readonly_fields when the user is student, but it threw an error saying "unknown fields".
just run the server, and log in (i made "admin" a student), and change or create a new article and you'll see the error.

**Comment by botanicvelious** [comment]
Try get_fields, see if you can find what they are, 

https://docs.djangoproject.com/en/2.1/ref/models/meta/

 Options.get_fields(include_parents=True, include_hidden=False)[source]¶

Could be that you arent accessing the correct field

**Comment by ghost** [comment]
@botanicvelious just checked the fields. Turns out there are 3 sets of fields from ArticleAdmin, ArticleForm and the Article model, which seems complicated and messy. Maybe I should make some changes to permissions instead of form fields. :)

**Comment by botanicvelious** [comment]
So long as the student cant change those fields however you go about it is fine by me! 👍
