### ISSUE TITLE
GSoC 2019 - Add user comments

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#51]
This task is to add a form to the bottom of a blog page that allows a logged in user to comment.

**Comment by OpusA** [comment]
Hi, I would love to look into this. Thanks!

**Comment by Flx0101** [comment]
@botanicvelious  I will take up the issue. Just i am a beginner so will you just elaborate that what key things i should cover like should work with django or django cms. And exactly the comment box should be placed where at the bottom of the page or specific location and comment should be displayed too?

**Comment by botanicvelious** [comment]
You would have to add a box at the bottom of the blog page that allows for someone to post a comment. then the comments would be displayed at the bottom under the blog post. Basically the same as most platforms such as wordpress etc. You would have to write the code for posting the comment, as well as storing the comment, as well as a template for displaying the comments.

For example something like the page https://www.django-cms.org/en/blog/2019/01/29/django-cms-3-6-released/ 

Note: they use disqus which we cant use for this, but the look and functionality should be similar.

**Comment by Flx0101** [comment]
Ohhk i will work on it and will try to complete asap.Thankyou for reply

**Comment by xaostheory** [comment]
Can i work on this? Also who is the desired actor? registered users can post a comment, only?

**Comment by botanicvelious** [comment]
Go for it, anyone should be able to post a comment, would be good to have something like reCAPTCHA v3 and a rate limit to prevent spam.

**Comment by sharmaadityaHQ** [comment]
@botanicvelious Can i take up this issue and redesign the comment feature if it has not been done yet?
