### ISSUE TITLE
GSoC 2019 - Add notice when page is unpublished.

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#53]
This task is to add a notice to a logged in user when a page is unpublished. Some sort of large red box at the top would do nicely.

**Comment by Saurabh-Singh-00** [comment]
```
from django.shortcuts import render
from aldryn_newsblog import models


def unpublished_article(request):
    unpublished = None
    if request.user.is_authenticated:
        unpublished = models.Article.objects.filter(author__user=request.user, is_published=False)
    return render(request, 'unpublished_notice.html', {'unpublished': unpublished})
```
I have created a demo view like this and this one does the required job but how should I integrate this with the djangocms?

![imageedit_4_5013573572](https://user-images.githubusercontent.com/36993159/54023966-5d827a80-41bc-11e9-9105-ac75373a101a.jpg)

**Comment by botanicvelious** [comment]
You can override the default template files.

**Comment by Saurabh-Singh-00** [comment]
So, should I have to override all the templates or only base.html would be enough?

**Comment by botanicvelious** [comment]
Whatever template you need to override to make it work. Dont just override everything for no reason, just the ones you need.

**Comment by Saurabh-Singh-00** [comment]
![imageedit_2_8563309557](https://user-images.githubusercontent.com/36993159/54086403-1e485b00-436f-11e9-9d83-a1e94eb65ffb.jpg)

I created a page named "unpublished-page" and kept it as unpublished. Now it shows a large red box at the top to admin if a page is unpublished. Is this what, exactly was required? It shows the red box only on unpublished page.

**Comment by botanicvelious** [comment]
Looks correct, make sure that only displays when someone is logged in!

**Comment by Saurabh-Singh-00** [comment]
@botanicvelious Is there something more required in this issue?
