### ISSUE TITLE
Default argument initialization with list found which is a loop hole in python

### ISSUE THREAD

**Issue by neel004** [python-gsoc/python-blogs#535]
**Describe the bug**
When an argument is initialized with an empty list in python, it retains previous values it has accumulated while executing the method.

**To Reproduce**
Link to code: https://github.com/python-gsoc/python-blogs/blob/master/aldryn_people/cms_toolbars.py#L47:

**Additional context**
Link for reference: https://web.archive.org/web/20200221224620id_/http://effbot.org/zone/default-values.htm

**Comment by vrac10** [comment]
Can I work on this issue?

**Comment by terriko** [comment]
Closing in preparation for archiving this repo.
