### ISSUE TITLE
GSoC 2019 - Add "is mentor" and "is suborg admin"

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#54]
This is to add a boolean field is_mentor and is_suborg_admin that ties a use to a specific suborg. For example the user is tied to PSF 2019 and is set to is_mentor, however, that same user may be tied to PSF 2018 and is_suborg_admin.

**Comment by sounak98** [comment]
The users are tied to the GSOC year by a many-to-many relationship. So we can't really be sure as to when a person was a mentor and when an admin and so on. I'm suggesting we add a `Role` table which will have the fields `role` and `year`. And an `Role` will have a many-to-one relationship with `GsocYear`. And `UserProfile` will have a field `role` which will have a many-to-many relationship with the `Role`. We just have to add a validator which will check that one user doesn't have multiple roles in a single year and something like one person who has been a mentor before can't add herself as a student.

What do you think @botanicvelious?

**Comment by botanicvelious** [comment]
You can have a many to many relationship where you set a user to the suborg and the year, then just have an additional relationship where the user for year x and suborg y is tied to role z

**Comment by botanicvelious** [comment]
Keep in mind, a user could be a suborg admin for one org, and a mentor for another.
