### ISSUE TITLE
GSoC 2019 - Add attachments to blogs

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#56]
This task is to add the ability to attach files to a blog post. Should be able to filter specific file types, ie .exe .bat .sh  etc

**Comment by amanpreets01** [comment]
Hello @botanicvelious I would like to work on this issue so how can I get started 
Like where exactly to integrate it or just a demo to show??

**Comment by botanicvelious** [comment]
It would be best to just add it to the ckeditor wysiwyg editor. That should make it easy to test as well etc.

**Comment by amanpreets01** [comment]
OK ,now where exactly should this be placed and how it should be managed ??
And what is exactly expected?Right now I am looking at docs of django-cms ,so any ref that could be helpful?

**Comment by botanicvelious** [comment]
I would add a button to the wysiwyg editor that allows you to attach and remove files from that blog post

Probably some popup button menu like there is for images.

**Comment by amanpreets01** [comment]
Ok I will do it and show it to you 👍

**Comment by amanpreets01** [comment]
I will try and show it to you

**Comment by Himanshu-Garg** [comment]
Anyone working on this?

**Comment by botanicvelious** [comment]
@amanpreets01 are you?

**Comment by amanpreets01** [comment]
@botanicvelious I think I need to learn more .
Himanshu you can surely work on this

**Comment by ghost** [comment]
I'll take this issue since there's no recent update
