### ISSUE TITLE
UnboundLocalError at schedule page

### ISSUE THREAD

**Issue by dotgourav** [python-gsoc/python-blogs#58]
**Describe the bug**
The error is occurring on visiting the [Schedule page](http://localhost:8000/en/schedule/).

**To Reproduce**
1. Go to '[Schedule page](http://localhost:8000/en/schedule/).'

**Screenshots**
![image](https://user-images.githubusercontent.com/2922351/53862917-45ff9200-4002-11e9-80b9-69aae34d7f55.png)

**Desktop (please complete the following information):**
 - OS: Fedora 27
 - Browser: Mozilla Firefox Developer Edition 66.0b12

**Additional information**
Timezone: UTC+4

**Comment by dotgourav** [comment]
@MastersAbh Can you take a look at it?

**Comment by MastersAbh** [comment]
Looking at it
