### ISSUE TITLE
GSoC 2019 - Add information tag for blogs

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#63]
This issue is to add a notification block that will display at the top of the screen that can be used to display data to a specific page when enabled. An initial example is a notification with a link to a students non GSoC blog. This would be enabled by the student on their own blog page so it would use the page-specific create permission in django cms.

**Comment by MastersAbh** [comment]
@botanicvelious So the students should be given the permission to enable it or disable it. 
So, this can be done by updating user model, keeping a column for this enable or disable ?

**Comment by botanicvelious** [comment]
It would be best done on the page, then the user who has access to the page would be able to update it.

**Comment by HAKSOAT** [comment]
@MastersAbh Are you working on this already?

**Comment by botanicvelious** [comment]
@HAKSOAT give it a go if you want!
