### ISSUE TITLE
GSoC 2019 - Auto disable users

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#66]
This issue is to add a feature so that you can set a date that the user will automatically have there account "active" status disabled. The date would be set in the user Home › Authentication and Authorization › Users › Test-Student1 and the check could be done as part of the run_cron command.

**Comment by sounak98** [comment]
@botanicvelious I will take this up.

Basically there will be a date when the user will be made inactive right?

**Comment by botanicvelious** [comment]
Correct as after gsoc is over the student user should not be able to login anymore.
