### ISSUE TITLE
GSoC 2019 - Custom registration url

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#67]
This issue is to create the ability to generate registration urls such as http://127.0.0.1:8000/en/register?id=56ac0bfd-5506-40d4-b2cb-eb30e02b8bec

Would have to be able to access these generated url's from a custom admin page, on that page would need to be able to see used/unused url's, generated date, and generate more

This url would be unique and only usable for one registration. It would bring the user to a page that would ask for user/pass/email and then create a user based on that information.

For the url unique string just use a RFC 4122 UUID

**Comment by ghost** [comment]
Will work on this! @botanicvelious
