### ISSUE TITLE
GSoC 2019 - Auto create google calendar

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#69]
This issue is to create an admin page that will talk to the google calendar api and auto add scheduled items to it. Would add an item by selecting a start and end date and time in UTC.

The admin page would also have a link to the public shared calander and the ical file from it.

**Comment by sounak98** [comment]
@botanicvelious will be taking this up!

**Comment by sounak98** [comment]
@botanicvelious what will be the end time for the scheduled items?

**Comment by botanicvelious** [comment]
Most would be all day events however some would have set day and times to end at.
