### ISSUE TITLE
GSoC 2019 - Add test framework

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#7]
This task is to add a test framework for the project, this would involve adding test frameworks such as Travis, landscape, and pylint integration files to test pr's before committing.

**Comment by mzfr** [comment]
@botanicvelious I can work on this issue. 
Can you provide some more information on this one like currently, this repo doesn't have any test so should I only add the `.travis.yml` file with only pylint command testing for code format? or is there any other things you want specifically?

**Comment by botanicvelious** [comment]
yes you would be adding the travis.yml files as well as pylint etc. Ideally also resolving issues found.

**Comment by mzfr** [comment]
@botanicvelious I can do that. Just another question - Is it important to use pylint? I mean I can use pycodestyle or flake8 instead of pylint?

**Comment by botanicvelious** [comment]
those also work, long as it meets the requirements of code style and linting
