### ISSUE TITLE
GSoC 2019 - Add a linter

### ISSUE THREAD

**Issue by dotgourav** [python-gsoc/python-blogs#75]
**Is your feature request related to a problem? Please describe.**
Add linting support. Linting would help us maintain code quality and hence help new contributors understand the code better.

**Describe the solution you'd like**
Add flake8 with these plugins: flake8-docstrings, pep8-naming, flake8-import-order

I suggest using the [Pre-commit](https://pre-commit.com/) framework for doing it. This would automate the checking of predefined hooks like flake8(https://flake8.pycqa.org/en/latest/user/using-hooks.html)

**Comment by botanicvelious** [comment]
Related to #7

**Comment by dotgourav** [comment]
I believe #7 should be broken down into issues such as:
- Add linting support
- Add travis CI with linting configuration
- Add test suite & update Travis CI config for running tests

Since 1 & 2 can be done fairly quickly and the project could use it right now as there are over 100 PEP8,PEP257 violations.

@botanicvelious What are your thoughts on it?

**Comment by botanicvelious** [comment]
Oh, I wasn't saying to add tests, just the framework, 👍

**Comment by sharmaadityaHQ** [comment]
I would like to take this up. Please guide me on how to get started with this.

**Comment by botanicvelious** [comment]
you would need to look at adding the approprate files, such as pylint.cfg landscape.yml and travis.yml for example
