### ISSUE TITLE
GSoC 2019: Use this issue for discussion gsoc 

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#8]
Please use this issue for any Google Summer of Code-related questions and discussion that does not fit elsewhere.

**Comment by MastersAbh** [comment]
Hey, This is Abhinav, final year undergrad at National Institute of Technology Patna. I am fluent with Python and have been programming in it for past three years. I am also well versed in django. 
I look forward to contributions in PSF project Python-gsoc. Could you help me proceed with the same?

**Comment by botanicvelious** [comment]
The information on the project is [http://python-gsoc.org/psf_ideas.html](http://python-gsoc.org/psf_ideas.html) you will need to make at least one pull request, there are a number of issues currently open, you can pick any one of those to work on. If you need help with the issue just let me know.

**Comment by jeffysam6** [comment]
Hello @botanicvelious,
I'm Jeffy John Sam  doing my 2nd year Bachelore of Engineering at Fr. C. Rodrigues Institute of Technology Mumbai.
In the past i have worked on some django and flask projects.
I want to contribute to Python-GSoC Blogging platform, so i will start off by working on the issues which are currently open .
I would love to stay with this community and contribute as much  in the future.
Thank you :)

**Comment by codestryker** [comment]
Hello Sir,
I am Samyak Jain.I am currently in 2nd year of B.Tech Computer Science at Teerthanker Mahaveer University.
I have two year experience in HTML,CSS,JavaScript,jQuery,SQL and one year experience in  Python,django,django-cms.I also worked on more than one open source github projects.
I want to make contribution in python-gsoc blogging platform and i will soon make a pull request for this project.

**Comment by kiran-glitch** [comment]
Hi everyone , I am Kiran  Khanna from Hyderabad , I Studying in Amrita  Vishwa Vidyapeetham I am in 2year of Engineering and I am interested in contributing to the python organization .

**Comment by priyanshu-panwar** [comment]
Hi everyone, I am Priyanshu Panwar, prefinal year student of National Institute of Technology, Jalandahr. I am a Python Django Freelancer and am very much interersted in contributing to python organisation and taking part in this coming GSOC.

**Comment by Aditya-Komaravolu** [comment]
@botanicvelious  Hi, this is Aditya, a Second Year Artificial Intelligence Undergraduate at Vidya Jyothi Institute of Technology,Hyderabad,Telangana,India. I am really interested to contribute and work on open source projects for Python organisation and want to be a part of GSoC 2021 under Python Organisation.I am interested to work in the areas of Machine learning and Python development.
Please help me to become an active contributor and help me be a part of Google Summer of Code 2021.

**Comment by botanicvelious** [comment]
the PSF is accepting at most one student this year, as such we recommend applying to other sub-organizations. You can find the other organizations on the [Project Ideas](https://python-gsoc.org/ideas.html) page. If you are still interested we will only be accepting a student who already has a knowledge of Django and Python.

**Comment by AmPhIbIaN26** [comment]
i wanted to ask can I submit multiple proposals for python, since it has multiple sub orgs and I would like to submit a proposal for 2 of them

**Comment by bedeveloper123** [comment]
Hello @botanicvelious ,
This is Bharat H. I'm beginner contributor for GSOC Python & gone through idea list of PSF organization. 
Trying to fix one of the issue from existing issue on "python-blogs" repo,  I pulled "python-blogs" repo into my local machine git(OS: Ubuntu 20.04 LTS) . Installed required supporting applications successfully. But the problem is I'm getting when I execute the **python3 manage.py runserver 0.0.0.0:8000** cmd getting an exception error like "django.core.exceptions.AppRegisterNotReady: Apps aren't loaded yet". 
Please help me on this...! how I can fix it.
