### ISSUE TITLE
UI inconsistencies

### ISSUE THREAD

**Issue by sounak98** [python-gsoc/python-blogs#83]
Some UI elements of the website are inconsistent. These examples will help understanding them better.

- The top bar is not fixed to the top and the height doesn't match.
![Screenshot 2019-03-27 at 2 13 03 PM](https://user-images.githubusercontent.com/22390515/55061869-cdd53b00-509a-11e9-84f4-17529df9b00c.png)

- In mobile view the top bar breaks and also it is impossible to access the menu. 
![Screenshot 2019-03-27 at 2 13 25 PM](https://user-images.githubusercontent.com/22390515/55061872-cf9efe80-509a-11e9-8565-d3dee693033a.png)

- The notifications on the top goes below the sidebar.
![Screenshot 2019-03-27 at 2 13 56 PM](https://user-images.githubusercontent.com/22390515/55061876-d168c200-509a-11e9-86a2-bdf10a786721.png)

These can be fixed to get a responsive and clean UI.

**Comment by ghost** [comment]
I thought I did great here..... 👍

**Comment by Karna98** [comment]
![Screencast from Sunday 31 March 2019 12:52:30  IST](https://user-images.githubusercontent.com/32186983/55286259-ef923300-53b6-11e9-8132-16ab09499dc8.gif)
Issue From Latest Patch From PR https://github.com/python-gsoc/python-blogs/pull/91
