### ISSUE TITLE
GSOC 2019  Edit Button throwing error due to undefined variable CLIPBOARD_BREAK

### ISSUE THREAD

**Issue by Karna98** [python-gsoc/python-blogs#87]
**Describe the bug**
name 'CLIPBOARD_BREAK' is not defined

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'http://0.0.0.0:8000/en/'
2. Click on 'Edit' Button on the nav bar.
3. See error

**Expected behaviour**
On Pressing the **edit** button it should redirect to edit page.
**Screenshots**
![Screenshot from 2019-03-29 21-26-10](https://user-images.githubusercontent.com/32186983/55245586-6d482880-5269-11e9-9872-f8a8f0a6338e.png)

**Comment by sounak98** [comment]
There was already a PR fixing this!

Check https://github.com/python-gsoc/python-blogs/pull/82.

**Comment by Karna98** [comment]
There was no issue describing this bug.
So didn't come across the pull request.

**Comment by botanicvelious** [comment]
no problem! 👍
