### ISSUE TITLE
GSoC 2019 - 403 on login sometimes 

### ISSUE THREAD

**Issue by botanicvelious** [python-gsoc/python-blogs#92]
Sometimes when you login you get a 403, this happens on firefox for sure no idea about other browsers.

[https://i.imgur.com/jak26S7.png](https://i.imgur.com/jak26S7.png)
```
Level | Time | Channel | Message | Location
-- | -- | -- | -- | --
WARNING | 03:01:06 03/31/2019 | django.security.csrf | Forbidden (CSRF token missing or incorrect.): /en/cms_login/ | C:\Users\matthew\AppData\Local\Programs\Python\Python37\lib\site-packages\django\utils\log.py:228
```

**Comment by sounak98** [comment]
@botanicvelious I debugged it a bit. The first time a user logs in the `csrf_cookie` gets stored. But when the user tries to log in for the second time the old `csrf_cookie` is being used whereas a new cookie should be generated.

**Comment by sounak98** [comment]
@botanic I think this can be reproduced with the following steps:

- login using the top bar
- logout by selecting the option from the topbar
- try to login again using the top bar
- this gives 403 csrf verification failed

Are others also able to reproduce this? This happens on Firefox, Chrome. Safari behaves very very weirdly though 😛

**Comment by Saurabh-Singh-00** [comment]
> Are others also able to reproduce this? This happens on Firefox, Chrome. Safari behaves very very weirdly though 😛

Yes the issue can be reproduced.

**Comment by sounak98** [comment]
I'll check it out

**Comment by Saurabh-Singh-00** [comment]
> I'll check it out

The problem is even after logging out the csrf token is saved in the cookies.

**Comment by sounak98** [comment]
> The problem is even after logging out the csrf token is saved in the cookies.

Yeah I noticed, probably it is getting cached or something.
